import { sql } from 'kysely';
import type { CraftingCollectResult,CraftingOrderView,CraftingRecipeView,CraftingStationKind,CraftingStationView } from '@eclipse/shared';
import { db } from '../../infra/db';

type Point={x:number;y:number;z:number};
interface StationRow{id:string;key:string;kind:CraftingStationKind;name:string;position_x:string;position_y:string;position_z:string;radius:string;}
interface RecipeRow{key:string;station_kind:CraftingStationKind;name:string;output_item_key:string;output_name:string;output_quantity:number;duration_seconds:number;level_required:number;}
interface OrderRow{id:string;station_id:string;recipe_key:string;recipe_name:string;batches:number;output_name:string;output_quantity:number;ready_at:Date;created_at:Date;status:'queued'|'claimed'|'cancelled';}
const distance=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);
const stationPoint=(s:StationRow):Point=>({x:Number(s.position_x),y:Number(s.position_y),z:Number(s.position_z)});
const toStation=(s:StationRow):CraftingStationView=>({id:s.id,key:s.key,kind:s.kind,name:s.name,position:stationPoint(s),radius:Number(s.radius)});
const toOrder=(r:OrderRow):CraftingOrderView=>({id:r.id,stationId:r.station_id,recipeKey:r.recipe_key,recipeName:r.recipe_name,batches:r.batches,outputName:r.output_name,outputQuantity:r.output_quantity*r.batches,readyAt:r.ready_at.toISOString(),createdAt:r.created_at.toISOString(),status:r.status,ready:r.status==='queued'&&r.ready_at.getTime()<=Date.now()});
export const listStations=async():Promise<CraftingStationView[]>=>{const q=await sql<StationRow>`SELECT id::text,key,kind,name,position_x::text,position_y::text,position_z::text,radius::text FROM crafting_stations WHERE enabled=TRUE ORDER BY name`.execute(db());return q.rows.map(toStation);};
export const listRecipes=async():Promise<CraftingRecipeView[]>=>{const q=await sql<RecipeRow>`SELECT r.key,r.station_kind,r.name,r.output_item_key,d.name output_name,r.output_quantity,r.duration_seconds,r.level_required FROM crafting_recipes r JOIN item_definitions d ON d.key=r.output_item_key WHERE r.enabled=TRUE ORDER BY r.station_kind,r.level_required,r.name`.execute(db());const inputs=await sql<{recipe_key:string;item_key:string;name:string;quantity:number}>`SELECT i.recipe_key,i.item_key,d.name,i.quantity FROM crafting_recipe_inputs i JOIN item_definitions d ON d.key=i.item_key ORDER BY i.recipe_key,d.name`.execute(db());return q.rows.map(r=>({key:r.key,stationKind:r.station_kind,name:r.name,outputItemKey:r.output_item_key,outputName:r.output_name,outputQuantity:r.output_quantity,durationSeconds:r.duration_seconds,levelRequired:r.level_required,ingredients:inputs.rows.filter(i=>i.recipe_key===r.key).map(i=>({itemKey:i.item_key,name:i.name,quantity:i.quantity}))}));};
export const listOrders=async(characterId:number):Promise<CraftingOrderView[]>=>{const q=await sql<OrderRow>`SELECT o.id::text,o.station_id::text,o.recipe_key,r.name recipe_name,o.batches,d.name output_name,r.output_quantity,o.ready_at,o.created_at,o.status FROM crafting_orders o JOIN crafting_recipes r ON r.key=o.recipe_key JOIN item_definitions d ON d.key=r.output_item_key WHERE o.character_id=${characterId} ORDER BY o.created_at DESC LIMIT 50`.execute(db());return q.rows.map(toOrder);};
const getStation=async(id:string,trx=db()):Promise<StationRow>=>{const q=await sql<StationRow>`SELECT id::text,key,kind,name,position_x::text,position_y::text,position_z::text,radius::text FROM crafting_stations WHERE id=${id}::uuid AND enabled=TRUE`.execute(trx);if(!q.rows[0])throw new Error('CRAFT_STATION_NOT_FOUND');return q.rows[0];};
const assertNear=(player:PlayerMp,s:StationRow)=>{if(distance(player.position,stationPoint(s))>Number(s.radius)+1)throw new Error('CRAFT_TOO_FAR');};
const ensureInventory=async(characterId:number,trx:any):Promise<{id:string;capacity_weight:string;slots:number}>=>{await sql`INSERT INTO inventories(owner_type,owner_id) VALUES('character',${characterId}) ON CONFLICT(owner_type,owner_id) DO NOTHING`.execute(trx);const q=await sql<{id:string;capacity_weight:string;slots:number}>`SELECT id::text,capacity_weight::text,slots FROM inventories WHERE owner_type='character' AND owner_id=${characterId} FOR UPDATE`.execute(trx);if(!q.rows[0])throw new Error('INVENTORY_NOT_FOUND');return q.rows[0];};
const consumeInput=async(inventoryId:string,itemKey:string,needed:number,trx:any):Promise<void>=>{const q=await sql<{id:string;quantity:number}>`SELECT id::text,quantity FROM inventory_items WHERE inventory_id=${inventoryId}::bigint AND item_key=${itemKey} ORDER BY id FOR UPDATE`.execute(trx);if(q.rows.reduce((s,x)=>s+x.quantity,0)<needed)throw new Error('CRAFT_MATERIALS_MISSING');let left=needed;for(const row of q.rows){if(left<=0)break;const take=Math.min(left,row.quantity);if(take===row.quantity)await sql`DELETE FROM inventory_items WHERE id=${row.id}::bigint`.execute(trx);else await sql`UPDATE inventory_items SET quantity=quantity-${take},updated_at=NOW() WHERE id=${row.id}::bigint`.execute(trx);left-=take;}};
export const startProduction=async(characterId:number,player:PlayerMp,stationId:string,recipeKey:string,batches:number):Promise<CraftingOrderView>=>{if(!Number.isInteger(batches)||batches<1||batches>20)throw new Error('CRAFT_INVALID_BATCHES');const station=await getStation(stationId);assertNear(player,station);return db().transaction().execute(async trx=>{const lockedStation=await getStation(stationId,trx);assertNear(player,lockedStation);const r=await sql<RecipeRow>`SELECT r.key,r.station_kind,r.name,r.output_item_key,d.name output_name,r.output_quantity,r.duration_seconds,r.level_required FROM crafting_recipes r JOIN item_definitions d ON d.key=r.output_item_key WHERE r.key=${recipeKey} AND r.enabled=TRUE`.execute(trx),recipe=r.rows[0];if(!recipe||recipe.station_kind!==lockedStation.kind)throw new Error('CRAFT_RECIPE_NOT_AVAILABLE');const ch=await sql<{level:number}>`SELECT level FROM characters WHERE id=${characterId} AND deleted_at IS NULL FOR UPDATE`.execute(trx);if(!ch.rows[0])throw new Error('CHARACTER_NOT_FOUND');if(ch.rows[0].level<recipe.level_required)throw new Error('CRAFT_LEVEL_REQUIRED');const active=await sql<{count:string}>`SELECT COUNT(*)::text count FROM crafting_orders WHERE character_id=${characterId} AND status='queued'`.execute(trx);if(Number(active.rows[0]?.count??0)>=5)throw new Error('CRAFT_QUEUE_FULL');const inventory=await ensureInventory(characterId,trx);const inputs=await sql<{item_key:string;quantity:number}>`SELECT item_key,quantity FROM crafting_recipe_inputs WHERE recipe_key=${recipeKey} ORDER BY item_key`.execute(trx);for(const input of inputs.rows)await consumeInput(inventory.id,input.item_key,input.quantity*batches,trx);const readySeconds=recipe.duration_seconds*batches;const q=await sql<OrderRow>`INSERT INTO crafting_orders(character_id,station_id,recipe_key,batches,ready_at) VALUES(${characterId},${stationId}::uuid,${recipeKey},${batches},NOW()+(${readySeconds}*INTERVAL '1 second')) RETURNING id::text,station_id::text,recipe_key,${recipe.name}::text recipe_name,batches,${recipe.output_name}::text output_name,${recipe.output_quantity}::int output_quantity,ready_at,created_at,status`.execute(trx);return toOrder(q.rows[0]!);});};
const addOutput=async(inventory:{id:string;capacity_weight:string;slots:number},itemKey:string,quantity:number,trx:any):Promise<void>=>{const d=await sql<{weight:string;stack_size:number}>`SELECT weight::text,stack_size FROM item_definitions WHERE key=${itemKey}`.execute(trx);if(!d.rows[0])throw new Error('CRAFT_OUTPUT_NOT_FOUND');const used=await sql<{weight:string}>`SELECT COALESCE(SUM(ii.quantity*d.weight),0)::text weight FROM inventory_items ii JOIN item_definitions d ON d.key=ii.item_key WHERE ii.inventory_id=${inventory.id}::bigint`.execute(trx);if(Number(used.rows[0]?.weight??0)+Number(d.rows[0].weight)*quantity>Number(inventory.capacity_weight)+1e-6)throw new Error('INVENTORY_OVERWEIGHT');const stacks=await sql<{id:string;quantity:number}>`SELECT id::text,quantity FROM inventory_items WHERE inventory_id=${inventory.id}::bigint AND item_key=${itemKey} AND quantity<${d.rows[0].stack_size} ORDER BY id FOR UPDATE`.execute(trx);let left=quantity;for(const s of stacks.rows){if(left<=0)break;const add=Math.min(left,d.rows[0].stack_size-s.quantity);await sql`UPDATE inventory_items SET quantity=quantity+${add},updated_at=NOW() WHERE id=${s.id}::bigint`.execute(trx);left-=add;}if(left<=0)return;const occupied=await sql<{slot:number}>`SELECT slot FROM inventory_items WHERE inventory_id=${inventory.id}::bigint ORDER BY slot FOR UPDATE`.execute(trx);const usedSlots=new Set(occupied.rows.map(x=>x.slot));const free:number[]=[];for(let i=0;i<inventory.slots;i++)if(!usedSlots.has(i))free.push(i);const neededSlots=Math.ceil(left/d.rows[0].stack_size);if(free.length<neededSlots)throw new Error('INVENTORY_NO_SLOTS');for(let i=0;i<neededSlots;i++){const add=Math.min(left,d.rows[0].stack_size);await sql`INSERT INTO inventory_items(inventory_id,item_key,slot,quantity,metadata) VALUES(${inventory.id}::bigint,${itemKey},${free[i]},${add},'{}'::jsonb)`.execute(trx);left-=add;}};
export const collectProduction=async(characterId:number,player:PlayerMp,orderId:string):Promise<CraftingCollectResult>=>db().transaction().execute(async trx=>{const q=await sql<OrderRow&{station_kind:CraftingStationKind;station_x:string;station_y:string;station_z:string;station_radius:string;output_item_key:string}>`SELECT o.id::text,o.station_id::text,o.recipe_key,r.name recipe_name,o.batches,d.name output_name,r.output_quantity,o.ready_at,o.created_at,o.status,s.kind station_kind,s.position_x::text station_x,s.position_y::text station_y,s.position_z::text station_z,s.radius::text station_radius,r.output_item_key FROM crafting_orders o JOIN crafting_recipes r ON r.key=o.recipe_key JOIN item_definitions d ON d.key=r.output_item_key JOIN crafting_stations s ON s.id=o.station_id WHERE o.id=${orderId}::uuid AND o.character_id=${characterId} FOR UPDATE OF o`.execute(trx),o=q.rows[0];if(!o)throw new Error('CRAFT_ORDER_NOT_FOUND');if(o.status!=='queued')throw new Error('CRAFT_ALREADY_CLAIMED');if(o.ready_at.getTime()>Date.now())throw new Error('CRAFT_NOT_READY');if(distance(player.position,{x:Number(o.station_x),y:Number(o.station_y),z:Number(o.station_z)})>Number(o.station_radius)+1)throw new Error('CRAFT_TOO_FAR');const inv=await ensureInventory(characterId,trx);await addOutput(inv,o.output_item_key,o.output_quantity*o.batches,trx);await sql`UPDATE crafting_orders SET status='claimed',claimed_at=NOW() WHERE id=${orderId}::uuid`.execute(trx);return{order:toOrder({...o,status:'claimed'}),inventoryUpdated:true};});
