import { sql } from 'kysely';
import type { DealershipOfferView,DealershipPurchaseResult,DealershipTestDriveResult } from '@eclipse/shared';
import { db } from '../../infra/db';

interface OfferRow{id:string;dealership_id:string;dealership_name:string;model:string;display_name:string;price:string;stock:number;position_x:string;position_y:string;position_z:string;}
const view=(r:OfferRow):DealershipOfferView=>({id:r.id,dealershipId:r.dealership_id,dealershipName:r.dealership_name,model:r.model,displayName:r.display_name,price:r.price,stock:r.stock,position:{x:Number(r.position_x),y:Number(r.position_y),z:Number(r.position_z)}});
const distance=(a:{x:number;y:number;z:number},b:{x:number;y:number;z:number})=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);
const getOffer=async(id:string,trx=db()):Promise<OfferRow>=>{const r=await sql<OfferRow>`SELECT o.id,o.dealership_id,d.name dealership_name,o.model,o.display_name,o.price,o.stock,d.position_x,d.position_y,d.position_z FROM dealership_offers o JOIN dealerships d ON d.id=o.dealership_id WHERE o.id=${id}::uuid AND o.enabled=TRUE`.execute(trx);if(!r.rows[0])throw new Error('OFFER_NOT_FOUND');return r.rows[0];};
export const listOffers=async():Promise<DealershipOfferView[]>=>{const r=await sql<OfferRow>`SELECT o.id,o.dealership_id,d.name dealership_name,o.model,o.display_name,o.price,o.stock,d.position_x,d.position_y,d.position_z FROM dealership_offers o JOIN dealerships d ON d.id=o.dealership_id WHERE o.enabled=TRUE ORDER BY d.name,o.price`.execute(db());return r.rows.map(view);};
export const purchase=async(characterId:number,player:PlayerMp,offerId:string):Promise<DealershipPurchaseResult>=>db().transaction().execute(async trx=>{const offer=await getOffer(offerId,trx);if(distance(player.position,{x:Number(offer.position_x),y:Number(offer.position_y),z:Number(offer.position_z)})>18)throw new Error('TOO_FAR');const locked=await sql<OfferRow>`SELECT o.id,o.dealership_id,d.name dealership_name,o.model,o.display_name,o.price,o.stock,d.position_x,d.position_y,d.position_z FROM dealership_offers o JOIN dealerships d ON d.id=o.dealership_id WHERE o.id=${offerId}::uuid AND o.enabled=TRUE FOR UPDATE OF o`.execute(trx),o=locked.rows[0];if(!o)throw new Error('OFFER_NOT_FOUND');if(o.stock<1)throw new Error('OUT_OF_STOCK');const ch=await trx.selectFrom('characters').select('id').where('id','=',characterId).where(sql<boolean>`bank>=${o.price}::numeric`).forUpdate().executeTakeFirst();if(!ch)throw new Error('INSUFFICIENT_FUNDS');const updated=await trx.updateTable('characters').set({bank:sql<string>`bank-${o.price}::numeric`,updated_at:new Date()}).where('id','=',characterId).returning('bank').executeTakeFirstOrThrow();await sql`UPDATE dealership_offers SET stock=stock-1 WHERE id=${offerId}::uuid`.execute(trx);const vin=`E${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).slice(2,8).toUpperCase()}`.slice(0,24);const vehicle=await sql<{id:string;vin:string}>`INSERT INTO vehicles(owner_character_id,model,vin,fuel,locked) VALUES(${characterId},${o.model},${vin},100,TRUE) RETURNING id::text,vin`.execute(trx);await trx.insertInto('economy_ledger').values({character_id:characterId,family_id:null,source:'dealership_purchase',direction:'sink',amount:o.price,metadata:{offerId,vehicleId:vehicle.rows[0]!.id}}).execute();return{vehicleId:vehicle.rows[0]!.id,vin:vehicle.rows[0]!.vin,model:o.model,displayName:o.display_name,bank:updated.bank};});

const drives=new Map<number,{entity:VehicleMp;timer:ReturnType<typeof setTimeout>}>();
const clearDrive=(playerId:number)=>{const d=drives.get(playerId);if(!d)return;clearTimeout(d.timer);if(mp.vehicles.exists(d.entity))d.entity.destroy();drives.delete(playerId);};
export const startTestDrive=async(player:PlayerMp,offerId:string):Promise<DealershipTestDriveResult>=>{const o=await getOffer(offerId);const p={x:Number(o.position_x),y:Number(o.position_y),z:Number(o.position_z)};if(distance(player.position,p)>18)throw new Error('TOO_FAR');clearDrive(player.id);const entity=mp.vehicles.new(mp.joaat(o.model),new mp.Vector3(p.x+5,p.y,p.z),{heading:player.heading,numberPlate:'TEST',locked:false,engine:true,dimension:player.dimension});const expiresAt=new Date(Date.now()+5*60_000);const timer=setTimeout(()=>clearDrive(player.id),5*60_000);drives.set(player.id,{entity,timer});return{offerId,expiresAt:expiresAt.toISOString()};};
export const cleanupTestDrive=(playerId:number)=>clearDrive(playerId);
