import { ErrorCode,RpcEvent,ServerEvent,SessionState,err,ok,type MedicalActionResult,type MedicalTargetRequest } from '@eclipse/shared';import { onRpc } from '../../core/rpc';import { sessions } from '../../core/session';import * as medical from './medicalEmergency.service';
const hospital=new mp.Vector3(307.3,-595.3,43.3);const target=(actor:PlayerMp,targetPlayerId:number)=>{if(!Number.isInteger(targetPlayerId))return null;const p=mp.players.at(targetPlayerId);if(!p||!mp.players.exists(p)||p===actor||p.dimension!==actor.dimension)return null;const s=sessions.get(p);if(!s||s.state!==SessionState.Playing||s.characterId===null)return null;const a=actor.position,b=p.position;if(Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z)>4)return null;return{player:p,characterId:s.characterId};};
const push=(p:PlayerMp,state:any)=>{if(mp.players.exists(p))p.call(ServerEvent.MedicalState,[JSON.stringify(state)]);};const stripWeapons=(p:PlayerMp)=>{if(mp.players.exists(p))p.call(ServerEvent.WeaponLoadout,[JSON.stringify([])]);};const map=(e:unknown)=>{const c=e instanceof Error?e.message:'';if(c==='NO_ACCESS')return err(ErrorCode.Unauthorized,{reason:'ems_access'});if(c==='NOT_DOWNED')return err(ErrorCode.Validation,{reason:'not_downed'});throw e;};
const placeHospital=(p:PlayerMp)=>{stripWeapons(p);p.spawn(hospital);p.dimension=0;p.health=100;p.armour=0;};
export const registerMedicalEmergencyModule=():void=>{
 onRpc<MedicalTargetRequest,MedicalActionResult>(RpcEvent.MedicalRevive,async(ctx,p)=>{const actor=ctx.session.characterId,t=target(ctx.player,p?.targetPlayerId);if(actor===null||!t)return err(ErrorCode.Validation,{reason:'target_not_nearby'});try{const state=await medical.revive(actor,t.characterId);t.player.health=35;push(t.player,state);return ok({success:true,state,health:35});}catch(e){return map(e);}});
 onRpc<MedicalTargetRequest,MedicalActionResult>(RpcEvent.MedicalHospitalize,async(ctx,p)=>{const actor=ctx.session.characterId,t=target(ctx.player,p?.targetPlayerId);if(actor===null||!t)return err(ErrorCode.Validation,{reason:'target_not_nearby'});try{const state=await medical.hospitalize(t.characterId,actor);placeHospital(t.player);push(t.player,state);return ok({success:true,state,health:100});}catch(e){return map(e);}});
 mp.events.add('playerDeath',(player:PlayerMp,_reason:any,_killer:any)=>{const s=sessions.get(player);if(!s||s.state!==SessionState.Playing||s.characterId===null)return;stripWeapons(player);const pos=player.position,dimension=player.dimension;void medical.markDowned(s.characterId).then(state=>{setTimeout(()=>{if(!mp.players.exists(player))return;stripWeapons(player);player.spawn(new mp.Vector3(pos.x,pos.y,pos.z));player.dimension=dimension;player.health=20;push(player,state);},750);});});
 setInterval(()=>{void (async()=>{const expired=new Set(await medical.expiredDowned());if(expired.size===0)return;for(const {player,session} of sessions.playing()){if(session.characterId===null||!expired.has(session.characterId))continue;const state=await medical.hospitalize(session.characterId);placeHospital(player);push(player,state);}})();},5000);
};
