import type { MedicalRecordView,MedicalTreatResult,PoliceCitizenView,PoliceRecordView } from '@eclipse/shared';
import { db } from '../../infra/db';

const membership=async(characterId:number)=>db().selectFrom('organization_members as om').innerJoin('organizations as o','o.id','om.organization_id').innerJoin('organization_ranks as r','r.id','om.rank_id').select(['o.id','o.kind','om.on_duty','r.permissions']).where('om.character_id','=',characterId).executeTakeFirst();
const allowed=async(characterId:number,kind:string,permission:string)=>{const m=await membership(characterId);if(!m||m.kind!==kind||!m.on_duty)throw new Error('NO_ACCESS');const p=m.permissions as Record<string,unknown>;if(p.all!==true&&p[permission]!==true)throw new Error('NO_ACCESS');return m;};
const policeView=(r:any):PoliceRecordView=>({id:r.id,targetCharacterId:r.target_character_id,officerCharacterId:r.officer_character_id,kind:r.kind,reason:r.reason,amount:r.amount,wantedLevel:r.wanted_level,active:r.active,createdAt:r.created_at.toISOString(),resolvedAt:r.resolved_at?.toISOString()??null});
const medicalView=(r:any):MedicalRecordView=>({id:r.id,targetCharacterId:r.target_character_id,medicCharacterId:r.medic_character_id,diagnosis:r.diagnosis,treatment:r.treatment,healthBefore:r.health_before,healthAfter:r.health_after,createdAt:r.created_at.toISOString()});

export const getCitizen=async(officerId:number,targetId:number):Promise<PoliceCitizenView>=>{await allowed(officerId,'police','mdt');const c=await db().selectFrom('characters').select(['id','first_name','last_name']).where('id','=',targetId).where('deleted_at','is',null).executeTakeFirst();if(!c)throw new Error('CHARACTER_NOT_FOUND');const rows=await db().selectFrom('police_records').selectAll().where('target_character_id','=',targetId).orderBy('created_at','desc').limit(100).execute();const active=rows.filter(r=>r.active);return{characterId:c.id,name:`${c.first_name} ${c.last_name}`,activeWantedLevel:Math.max(0,...active.map(r=>r.wanted_level??0)),activeFines:active.filter(r=>r.kind==='fine').reduce((s,r)=>s+Number(r.amount??0),0).toFixed(2),records:rows.map(policeView)};};
export const createPoliceRecord=async(officerId:number,targetId:number,kind:'fine'|'wanted'|'note',reasonRaw:string,amount?:string,wantedLevel?:number):Promise<PoliceRecordView>=>{const m=await allowed(officerId,'police','mdt');const reason=reasonRaw.trim().slice(0,220);if(reason.length<3)throw new Error('INVALID_REASON');if(kind==='fine'&&(!amount||!/^\d{1,10}(?:\.\d{1,2})?$/.test(amount)||Number(amount)<=0))throw new Error('INVALID_AMOUNT');if(kind==='wanted'&&(!Number.isInteger(wantedLevel)||wantedLevel!<1||wantedLevel!>5))throw new Error('INVALID_WANTED');const row=await db().insertInto('police_records').values({target_character_id:targetId,officer_character_id:officerId,kind,reason,amount:kind==='fine'?amount!:null,wanted_level:kind==='wanted'?wantedLevel!:null}).returningAll().executeTakeFirstOrThrow();await db().insertInto('organization_audit_log').values({organization_id:m.id,actor_character_id:officerId,target_character_id:targetId,action:`police_${kind}`,metadata:{recordId:row.id}}).execute();return policeView(row);};
export const resolvePoliceRecord=async(officerId:number,recordId:string):Promise<void>=>{const m=await allowed(officerId,'police','mdt');const row=await db().updateTable('police_records').set({active:false,resolved_at:new Date()}).where('id','=',recordId).where('active','=',true).returning(['id','target_character_id']).executeTakeFirst();if(!row)throw new Error('RECORD_NOT_FOUND');await db().insertInto('organization_audit_log').values({organization_id:m.id,actor_character_id:officerId,target_character_id:row.target_character_id,action:'police_record_resolved',metadata:{recordId}}).execute();};
export const medicalHistory=async(medicId:number,targetId:number):Promise<MedicalRecordView[]>=>{await allowed(medicId,'ems','medical');const rows=await db().selectFrom('medical_records').selectAll().where('target_character_id','=',targetId).orderBy('created_at','desc').limit(100).execute();return rows.map(medicalView);};
export const treat=async(medicId:number,targetId:number,diagnosisRaw:string,treatmentRaw:string,healTo:number):Promise<MedicalTreatResult>=>{const m=await allowed(medicId,'ems','medical');const diagnosis=diagnosisRaw.trim().slice(0,220),treatment=treatmentRaw.trim().slice(0,220);if(diagnosis.length<3||treatment.length<3||!Number.isInteger(healTo)||healTo<1||healTo>100)throw new Error('INVALID_TREATMENT');const ch=await db().selectFrom('characters').select(['id','health']).where('id','=',targetId).where('deleted_at','is',null).executeTakeFirst();if(!ch)throw new Error('CHARACTER_NOT_FOUND');const row=await db().transaction().execute(async trx=>{await trx.updateTable('characters').set({health:healTo,updated_at:new Date()}).where('id','=',targetId).execute();return trx.insertInto('medical_records').values({target_character_id:targetId,medic_character_id:medicId,diagnosis,treatment,health_before:ch.health,health_after:healTo}).returningAll().executeTakeFirstOrThrow();});await db().insertInto('organization_audit_log').values({organization_id:m.id,actor_character_id:medicId,target_character_id:targetId,action:'medical_treatment',metadata:{recordId:row.id,healTo}}).execute();return{health:healTo,record:medicalView(row)};};
