import { sql } from 'kysely';
import type { FamilyContractView,FamilyStorageView,FamilyUpgradeView,FamilyVehicleView } from '@eclipse/shared';
import { db } from '../../infra/db';

type Member={familyId:string;rankIndex:number;permissions:Record<string,unknown>;};
const member=async(characterId:number):Promise<Member>=>{const r=await db().selectFrom('family_members as fm').innerJoin('family_ranks as fr','fr.id','fm.rank_id').select(['fm.family_id','fr.rank_index','fr.permissions']).where('fm.character_id','=',characterId).executeTakeFirst();if(!r)throw new Error('NOT_IN_FAMILY');return{familyId:r.family_id,rankIndex:r.rank_index,permissions:(r.permissions??{}) as Record<string,unknown>};};
const can=(m:Member,p:string)=>m.permissions.all===true||m.permissions[p]===true;
const audit=async(familyId:string,actor:number,action:string,metadata:Record<string,unknown>={})=>{await db().insertInto('family_audit_log').values({family_id:familyId,actor_character_id:actor,target_character_id:null,action,metadata}).execute();};

const spawned=new Map<string,{entity:VehicleMp;familyId:string}>();
const live=(id:string)=>{const x=spawned.get(id);if(x&&!mp.vehicles.exists(x.entity))spawned.delete(id);return spawned.has(id);};
export const vehicles=async(characterId:number):Promise<FamilyVehicleView[]>=>{const m=await member(characterId);const r=await sql<{id:string;model:string;vin:string;plate:string|null;locked:boolean}>`SELECT id::text,model,vin,plate,locked FROM vehicles WHERE owner_family_id=${m.familyId}::bigint ORDER BY id`.execute(db());return r.rows.map(v=>({...v,spawned:live(v.id)}));};
export const spawnVehicle=async(characterId:number,player:PlayerMp,vehicleId:string):Promise<FamilyVehicleView>=>{const m=await member(characterId);if(!can(m,'storage')&&!can(m,'vehicles'))throw new Error('NO_PERMISSION');if(live(vehicleId))throw new Error('VEHICLE_ALREADY_SPAWNED');const q=await sql<{id:string;model:string;vin:string;plate:string|null;locked:boolean}>`SELECT id::text,model,vin,plate,locked FROM vehicles WHERE id=${vehicleId}::bigint AND owner_family_id=${m.familyId}::bigint`.execute(db()),v=q.rows[0];if(!v)throw new Error('VEHICLE_NOT_FOUND');const h=player.heading*Math.PI/180,pos=new mp.Vector3(player.position.x+Math.sin(h)*4,player.position.y+Math.cos(h)*4,player.position.z);const entity=mp.vehicles.new(mp.joaat(v.model),pos,{heading:player.heading,numberPlate:(v.plate??'FAMILY').slice(0,8),locked:v.locked,engine:false,dimension:player.dimension});spawned.set(v.id,{entity,familyId:m.familyId});await audit(m.familyId,characterId,'family_vehicle_spawned',{vehicleId});return{...v,spawned:true};};
export const storeVehicle=async(characterId:number,vehicleId:string):Promise<void>=>{const m=await member(characterId),x=spawned.get(vehicleId);if(!x||x.familyId!==m.familyId||!mp.vehicles.exists(x.entity))throw new Error('VEHICLE_NOT_SPAWNED');x.entity.destroy();spawned.delete(vehicleId);await audit(m.familyId,characterId,'family_vehicle_stored',{vehicleId});};

const inventoryId=async(familyId:string):Promise<string>=>{const q=await sql<{id:string}>`INSERT INTO inventories(owner_type,owner_id,capacity_weight,slots) VALUES('family',${familyId}::bigint,300,60) ON CONFLICT(owner_type,owner_id) DO UPDATE SET owner_id=EXCLUDED.owner_id RETURNING id::text`.execute(db());return q.rows[0]!.id;};
export const storage=async(characterId:number):Promise<FamilyStorageView>=>{const m=await member(characterId);if(!can(m,'storage'))throw new Error('NO_PERMISSION');const id=await inventoryId(m.familyId);const h=await sql<{capacity_weight:string;slots:number;used_weight:string}>`SELECT i.capacity_weight::text,i.slots,COALESCE(SUM(ii.quantity*d.weight),0)::numeric(10,3)::text used_weight FROM inventories i LEFT JOIN inventory_items ii ON ii.inventory_id=i.id LEFT JOIN item_definitions d ON d.key=ii.item_key WHERE i.id=${id}::bigint GROUP BY i.id`.execute(db());const items=await sql<any>`SELECT ii.id::text,ii.item_key,ii.slot,ii.quantity,ii.metadata,d.name,d.category,d.weight::text,d.stack_size FROM inventory_items ii JOIN item_definitions d ON d.key=ii.item_key WHERE ii.inventory_id=${id}::bigint ORDER BY ii.slot`.execute(db());const x=h.rows[0]!;return{inventory:{inventoryId:id,capacityWeight:x.capacity_weight,usedWeight:x.used_weight,slots:x.slots,items:items.rows.map((i:any)=>({id:i.id,itemKey:i.item_key,name:i.name,category:i.category,slot:i.slot,quantity:i.quantity,weightEach:i.weight,stackSize:i.stack_size,metadata:i.metadata}))}};};
export const transferStorage=async(characterId:number,itemId:string,quantity:number,direction:'deposit'|'withdraw'):Promise<FamilyStorageView>=>{if(!Number.isInteger(quantity)||quantity<=0)throw new Error('INVALID_QUANTITY');const m=await member(characterId);if(!can(m,'storage'))throw new Error('NO_PERMISSION');const familyInv=await inventoryId(m.familyId);const ch=await sql<{id:string}>`SELECT id::text FROM inventories WHERE owner_type='character' AND owner_id=${characterId}`.execute(db());if(!ch.rows[0])throw new Error('ITEM_NOT_FOUND');const from=direction==='deposit'?ch.rows[0].id:familyInv,to=direction==='deposit'?familyInv:ch.rows[0].id;await db().transaction().execute(async trx=>{const q=await sql<{id:string;item_key:string;quantity:number;metadata:unknown}>`SELECT id::text,item_key,quantity,metadata FROM inventory_items WHERE id=${itemId}::bigint AND inventory_id=${from}::bigint FOR UPDATE`.execute(trx),item=q.rows[0];if(!item||item.quantity<quantity)throw new Error('ITEM_NOT_FOUND');const def=await sql<{stack_size:number}>`SELECT stack_size FROM item_definitions WHERE key=${item.item_key}`.execute(trx);const slots=await sql<{slots:number}>`SELECT slots FROM inventories WHERE id=${to}::bigint FOR UPDATE`.execute(trx);const occupied=await sql<{slot:number}>`SELECT slot FROM inventory_items WHERE inventory_id=${to}::bigint ORDER BY slot`.execute(trx),used=new Set(occupied.rows.map(r=>r.slot));let slot=-1;for(let i=0;i<(slots.rows[0]?.slots??0);i++)if(!used.has(i)){slot=i;break;}if(slot<0)throw new Error('STORAGE_FULL');if(item.quantity===quantity)await sql`DELETE FROM inventory_items WHERE id=${itemId}::bigint`.execute(trx);else await sql`UPDATE inventory_items SET quantity=quantity-${quantity},updated_at=NOW() WHERE id=${itemId}::bigint`.execute(trx);await sql`INSERT INTO inventory_items(inventory_id,item_key,slot,quantity,metadata) VALUES(${to}::bigint,${item.item_key},${slot},${quantity},${JSON.stringify(item.metadata??{})}::jsonb)`.execute(trx);});await audit(m.familyId,characterId,direction==='deposit'?'family_storage_deposit':'family_storage_withdraw',{itemId,quantity});return storage(characterId);};

export const contracts=async(characterId:number):Promise<FamilyContractView[]>=>{const m=await member(characterId);const r=await db().selectFrom('family_contracts').selectAll().where('family_id','=',m.familyId).where('expires_at','>',new Date()).orderBy('created_at','desc').execute();return r.map(x=>({id:x.id,contractKey:x.contract_key,progress:x.progress,target:x.target,rewardMoney:x.reward_money,rewardReputation:x.reward_reputation,expiresAt:x.expires_at.toISOString(),completedAt:x.completed_at?.toISOString()??null}));};
export const upgrades=async(characterId:number):Promise<FamilyUpgradeView[]>=>{const m=await member(characterId);const q=await sql<{upgrade_key:string;name:string;description:string;max_level:number;base_price:string;level:number}>`SELECT d.upgrade_key,d.name,d.description,d.max_level,d.base_price::text,COALESCE(u.level,0)::int level FROM family_upgrade_definitions d LEFT JOIN family_upgrades u ON u.upgrade_key=d.upgrade_key AND u.family_id=${m.familyId}::bigint ORDER BY d.upgrade_key`.execute(db());return q.rows.map(x=>({key:x.upgrade_key,name:x.name,description:x.description,level:x.level,maxLevel:x.max_level,nextPrice:x.level>=x.max_level?null:(Number(x.base_price)*(x.level+1)).toFixed(2)}));};
export const buyUpgrade=async(characterId:number,key:string):Promise<FamilyUpgradeView[]>=>{const m=await member(characterId);if(!can(m,'all')&&!can(m,'treasury'))throw new Error('NO_PERMISSION');await db().transaction().execute(async trx=>{const d=await sql<{max_level:number;base_price:string}>`SELECT max_level,base_price::text FROM family_upgrade_definitions WHERE upgrade_key=${key}`.execute(trx);if(!d.rows[0])throw new Error('UPGRADE_NOT_FOUND');const u=await sql<{level:number}>`SELECT level FROM family_upgrades WHERE family_id=${m.familyId}::bigint AND upgrade_key=${key} FOR UPDATE`.execute(trx),level=u.rows[0]?.level??0;if(level>=d.rows[0].max_level)throw new Error('UPGRADE_MAX');const price=(Number(d.rows[0].base_price)*(level+1)).toFixed(2);const f=await sql`SELECT id FROM families WHERE id=${m.familyId}::bigint AND balance>=${price}::numeric FOR UPDATE`.execute(trx);if(!f.rows[0])throw new Error('INSUFFICIENT_FAMILY_FUNDS');await sql`UPDATE families SET balance=balance-${price}::numeric,updated_at=NOW() WHERE id=${m.familyId}::bigint`.execute(trx);await sql`INSERT INTO family_upgrades(family_id,upgrade_key,level) VALUES(${m.familyId}::bigint,${key},${level+1}) ON CONFLICT(family_id,upgrade_key) DO UPDATE SET level=EXCLUDED.level,updated_at=NOW()`.execute(trx);if(key==='storage')await sql`UPDATE inventories SET slots=60+40*${level+1},capacity_weight=300+150*${level+1},updated_at=NOW() WHERE owner_type='family' AND owner_id=${m.familyId}::bigint`.execute(trx);});await audit(m.familyId,characterId,'family_upgrade_bought',{key});return upgrades(characterId);};
