<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RpcEvent,type BusinessPurchaseResult,type BusinessRestockResult,type BusinessSaleResult,type BusinessTreasuryResult,type BusinessView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
import StorePanel from './StorePanel.vue';

type Mode='owned'|'catalog';
const mode=ref<Mode>('owned');
const owned=ref<BusinessView[]>([]);const catalog=ref<BusinessView[]>([]);const busy=ref(false);const error=ref('');const notice=ref('');
const amounts=ref<Record<string,string>>({});const quantities=ref<Record<string,string>>({});const markups=ref<Record<string,string>>({});
const money=(v:string)=>Number(v).toLocaleString('ru-RU',{maximumFractionDigits:2});
const load=async()=>{const[o,c]=await Promise.all([rpc<BusinessView[]>(RpcEvent.BusinessOwned),rpc<BusinessView[]>(RpcEvent.BusinessCatalog)]);if(o.ok)owned.value=o.data;if(c.ok)catalog.value=c.data;};
const run=async<T>(event:string,payload:unknown,message:string):Promise<T|null>=>{if(busy.value)return null;busy.value=true;error.value='';notice.value='';try{const r=await rpc<T>(event,payload);if(!r.ok){error.value=r.code;return null;}notice.value=message;return r.data;}finally{busy.value=false;}};
const buy=async(id:string)=>{if(await run<BusinessPurchaseResult>(RpcEvent.BusinessBuy,{businessId:id},'Бизнес приобретён'))await load();};
const sell=async(id:string)=>{if(await run<BusinessSaleResult>(RpcEvent.BusinessSell,{businessId:id},'Бизнес продан государству'))await load();};
const transfer=async(event:string,b:BusinessView)=>{const a=amounts.value[b.id]??'';if(await run<BusinessTreasuryResult>(event,{businessId:b.id,amount:a},'Баланс обновлён')){amounts.value[b.id]='';await load();}};
const restock=async(b:BusinessView)=>{const quantity=Number(quantities.value[b.id]??0);if(await run<BusinessRestockResult>(RpcEvent.BusinessRestock,{businessId:b.id,quantity},'Поставка принята')){quantities.value[b.id]='';await load();}};
const markup=async(b:BusinessView)=>{const markupPercent=Number(markups.value[b.id]??b.markupPercent);if(await run<BusinessView>(RpcEvent.BusinessSetMarkup,{businessId:b.id,markupPercent},'Наценка изменена'))await load();};
onMounted(()=>void load());
</script>
<template><section class="business-panel"><div class="toolbar"><div><button :class="{active:mode==='owned'}" @click="mode='owned'">Мои бизнесы</button><button :class="{active:mode==='catalog'}" @click="mode='catalog'">Каталог</button></div><button @click="load">Обновить</button></div><p v-if="error" class="msg error">{{error}}</p><p v-if="notice" class="msg ok">{{notice}}</p><div v-if="mode==='catalog'" class="grid"><article v-for="b in catalog" :key="b.id"><header><div><small>{{b.kind}}</small><h3>{{b.name}}</h3></div><strong>${{money(b.price)}}</strong></header><p>Склад {{b.stock}} / {{b.stockCapacity}} · наценка {{b.markupPercent}}%</p><p>Координаты {{b.position.x.toFixed(1)}}, {{b.position.y.toFixed(1)}}</p><button v-if="!b.owned" :disabled="busy" @click="buy(b.id)">Купить с банковского счёта</button><span v-else>{{b.ownedByMe?'Принадлежит вам':'Уже куплен'}}</span></article></div><div v-else class="grid"><article v-for="b in owned" :key="b.id"><header><div><small>{{b.kind}}</small><h3>{{b.name}}</h3></div><strong>${{money(b.price)}}</strong></header><div class="stats"><span>Банк бизнеса <b>${{money(b.bankBalance)}}</b></span><span>Касса <b>${{money(b.cashBalance)}}</b></span><span>Склад <b>{{b.stock}} / {{b.stockCapacity}}</b></span></div><div class="row"><input v-model="amounts[b.id]" placeholder="Сумма"><button :disabled="busy" @click="transfer(RpcEvent.BusinessDeposit,b)">Внести</button><button :disabled="busy" @click="transfer(RpcEvent.BusinessWithdraw,b)">Вывести</button></div><div class="row"><input v-model="quantities[b.id]" placeholder="Кол-во товара"><button :disabled="busy" @click="restock(b)">Закупить по ${{money(b.wholesaleUnitCost)}}</button></div><div class="row"><input v-model="markups[b.id]" :placeholder="String(b.markupPercent)+'%'"><button :disabled="busy" @click="markup(b)">Изменить наценку</button></div><button class="danger" :disabled="busy" @click="sell(b.id)">Продать государству</button></article><p v-if="!owned.length" class="empty">У вас пока нет бизнеса.</p></div><StorePanel/></section></template>
<style scoped>.business-panel{display:grid;gap:14px}.toolbar{display:flex;justify-content:space-between}.toolbar>div{display:flex;gap:7px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}article{padding:16px;border:1px solid var(--e-border);border-radius:14px;background:var(--e-surface-1)}header{display:flex;justify-content:space-between;gap:14px}header h3{margin:4px 0}small{color:var(--e-accent);text-transform:uppercase}p,span{color:var(--e-text-muted);font-size:12px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.stats span{padding:8px;border-radius:9px;background:var(--e-surface-2)}.stats b{display:block;color:var(--e-text-primary);margin-top:3px}.row{display:flex;gap:7px;margin:8px 0}.row input{min-width:0;flex:1;border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);padding:9px}button{border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);padding:9px 12px;cursor:pointer}button.active{border-color:var(--e-accent);background:var(--e-accent-soft)}button:disabled{opacity:.45}.danger{color:#ff8585;margin-top:8px}.msg{padding:9px 12px;border-radius:9px}.error{background:rgba(255,80,80,.1);color:#ff8585}.ok{background:rgba(80,200,120,.1);color:#7dde9f}.empty{grid-column:1/-1;text-align:center;padding:25px}</style>
