<script setup lang="ts">
import { onMounted,ref } from 'vue';import { RpcEvent,type ActivityCompleteResult,type ActivitySessionView,type ActivityView,type CasinoGameResult,type CasinoHistoryView,type CasinoStateView } from '@eclipse/shared';import { rpc } from '../core/rpc';
const state=ref<CasinoStateView|null>(null),history=ref<CasinoHistoryView[]>([]),activities=ref<ActivityView[]>([]),session=ref<ActivitySessionView|null>(null),chips=ref(100),bet=ref(100),choice=ref<string>('red'),message=ref(''),busy=ref(false);
const load=async()=>{const[s,h,a]=await Promise.all([rpc<CasinoStateView>(RpcEvent.CasinoState),rpc<CasinoHistoryView[]>(RpcEvent.CasinoHistory),rpc<ActivityView[]>(RpcEvent.ActivityList)]);if(s.ok)state.value=s.data;if(h.ok)history.value=h.data;if(a.ok)activities.value=a.data;};
const exchange=async(direction:'buy'|'sell')=>{busy.value=true;const r=await rpc<CasinoStateView>(RpcEvent.CasinoExchange,{direction,chips:chips.value});busy.value=false;if(r.ok){state.value=r.data;message.value='Операция выполнена';}else message.value=r.code;};
const play=async(game:'slots'|'roulette'|'dice')=>{busy.value=true;const raw=game==='roulette'?(Number.isFinite(Number(choice.value))?Number(choice.value):choice.value):game==='dice'?Number(choice.value):undefined;const r=await rpc<CasinoGameResult>(RpcEvent.CasinoPlay,{game,bet:bet.value,choice:raw});busy.value=false;if(r.ok){state.value=state.value?{...state.value,chips:r.data.chips}:state.value;message.value=`Выплата: ${r.data.payout} фишек · ${JSON.stringify(r.data.result)}`;await load();}else message.value=r.code;};
const start=async(key:string)=>{const r=await rpc<ActivitySessionView>(RpcEvent.ActivityStart,{key});if(r.ok){session.value=r.data;message.value=r.data.kind==='reaction'?'Ждите сигнала и нажмите «Действие» после него.':'Следуйте к отмеченной точке и нажимайте «Действие».';}else message.value=r.code;};
const step=async()=>{const r=await rpc<ActivitySessionView|ActivityCompleteResult>(RpcEvent.ActivityStep);if(!r.ok){message.value=r.code;return;}if('rewardCash'in r.data){message.value=`Активность завершена: +$${r.data.rewardCash}`;session.value=null;await load();}else{session.value=r.data;message.value=`Этап ${r.data.step+1}/${r.data.totalSteps}`;}};
const cancel=async()=>{await rpc(RpcEvent.ActivityCancel);session.value=null;message.value='Активность отменена';};onMounted(()=>void load());
</script>
<template><div class="wrap"><section class="card"><header><div><small>DIAMOND CASINO</small><h2>{{state?.chips??0}} фишек</h2></div><span>1 фишка = $10</span></header><div class="row"><input v-model.number="chips" type="number" min="1"><button :disabled="busy" @click="exchange('buy')">Купить</button><button :disabled="busy" @click="exchange('sell')">Продать</button></div></section><section class="games"><article><b>Слоты</b><span>10–50 000 фишек</span><input v-model.number="bet" type="number" min="10"><button @click="play('slots')">Крутить</button></article><article><b>Рулетка</b><span>0–36 / red / black / even / odd</span><input v-model="choice"><button @click="play('roulette')">Ставка</button></article><article><b>Кости</b><span>Угадайте сумму 2–12</span><input v-model="choice"><button @click="play('dice')">Бросить</button></article></section><p class="msg">{{message}}</p><section><h3>Активности</h3><div v-if="session" class="active"><b>Активно: {{session.key}}</b><span>Этап {{session.step+1}} / {{Math.max(1,session.totalSteps)}}</span><button @click="step">Действие</button><button @click="cancel">Отменить</button></div><div class="activities"><article v-for="a in activities" :key="a.key"><div><b>{{a.name}}</b><small>{{a.description}}</small><span>${{a.rewardCash}} · {{a.completions}} завершений</span></div><button :disabled="!a.available||!!session" @click="start(a.key)">{{a.available?'Начать':a.nextAt?new Date(a.nextAt).toLocaleString('ru-RU'):'Недоступно'}}</button></article></div></section><section><h3>Последние игры</h3><div class="history"><span v-for="h in history.slice(0,12)" :key="h.id">{{h.game}} · ставка {{h.bet}} · выплата {{h.payout}}</span></div></section></div></template>
<style scoped>.wrap{display:grid;gap:14px}.card,.games article,.activities article,.active{border:1px solid var(--e-border);background:var(--e-surface-1);border-radius:14px;padding:14px}.card header,.row,.activities article,.active{display:flex;align-items:center;justify-content:space-between;gap:10px}.games{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.games article{display:grid;gap:8px}.games span,.activities small,.activities span,.history{color:var(--e-text-muted)}input{padding:9px;border:1px solid var(--e-border);border-radius:8px;background:var(--e-surface-2);color:#fff}.activities{display:grid;gap:8px}.activities article div{display:grid;gap:4px}.msg{min-height:20px;color:var(--e-accent)}.history{display:grid;grid-template-columns:repeat(2,1fr);gap:5px;font-size:12px}</style>