<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RpcEvent,type ClothingCatalogItem,type CustomizationShopView,type OutfitView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
const items=ref<ClothingCatalogItem[]>([]),shops=ref<CustomizationShopView[]>([]),busy=ref(false),error=ref('');
const load=async()=>{const[i,s]=await Promise.all([rpc<ClothingCatalogItem[]>(RpcEvent.ClothingCatalog),rpc<CustomizationShopView[]>(RpcEvent.CustomizationShops)]);if(i.ok)items.value=i.data;else error.value=i.code;if(s.ok)shops.value=s.data;};
const act=async(event:string,item:ClothingCatalogItem)=>{if(busy.value)return;busy.value=true;error.value='';const r=await rpc<OutfitView>(event,{itemKey:item.key});busy.value=false;if(!r.ok){error.value=r.code;return;}await load();};
const money=(v:string)=>Number(v).toLocaleString('ru-RU');
onMounted(()=>void load());
</script>
<template><section><p v-if="error" class="error">{{error}}</p><div class="shops"><article v-for="s in shops.filter(x=>x.kind==='clothing')" :key="s.id"><div><b>{{s.name}}</b><span>Покупка доступна рядом с магазином</span></div><small>{{s.position.x.toFixed(1)}}, {{s.position.y.toFixed(1)}}</small></article></div><h3>Каталог и гардероб</h3><div class="catalog"><article v-for="item in items" :key="item.key" :class="{equipped:item.equipped}"><div><small>{{item.category.toUpperCase()}}</small><b>{{item.name}}</b><span>Drawable {{item.drawable}} · Texture {{item.texture}}</span></div><strong>${{money(item.price)}}</strong><button v-if="!item.owned" :disabled="busy" @click="act(RpcEvent.ClothingBuy,item)">Купить и надеть</button><button v-else-if="!item.equipped" :disabled="busy" @click="act(RpcEvent.ClothingEquip,item)">Надеть</button><em v-else>Надето</em></article></div></section></template>
<style scoped>.shops,.catalog{display:grid;gap:9px}.shops{grid-template-columns:1fr 1fr;margin-bottom:20px}.shops article,.catalog article{padding:13px;border:1px solid var(--e-border);border-radius:11px;background:var(--e-surface-1)}.shops article{display:flex;justify-content:space-between}.shops article div,.catalog article>div{display:flex;flex-direction:column;gap:4px}.shops span,.shops small,.catalog span,.catalog small{color:var(--e-text-muted)}.catalog{grid-template-columns:repeat(3,1fr)}.catalog article{display:flex;flex-direction:column;gap:10px}.catalog button{padding:9px;border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);cursor:pointer}.catalog em{font-style:normal;color:#7ee0a0}.equipped{border-color:var(--e-accent)!important}.error{color:#ff8585}</style>