<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';
import { RpcEvent,type CraftingCollectResult,type CraftingOrderView,type CraftingRecipeView,type CraftingStationView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
const stations=ref<CraftingStationView[]>([]),recipes=ref<CraftingRecipeView[]>([]),orders=ref<CraftingOrderView[]>([]),stationId=ref(''),batches=ref<Record<string,number>>({}),busy=ref(false),error=ref(''),notice=ref(''),now=ref(Date.now());
const load=async()=>{const[s,r,o]=await Promise.all([rpc<CraftingStationView[]>(RpcEvent.CraftingStations),rpc<CraftingRecipeView[]>(RpcEvent.CraftingRecipes),rpc<CraftingOrderView[]>(RpcEvent.CraftingOrders)]);if(s.ok){stations.value=s.data;if(!stationId.value&&s.data[0])stationId.value=s.data[0].id;}if(r.ok)recipes.value=r.data;if(o.ok)orders.value=o.data;};
const selected=computed(()=>stations.value.find(s=>s.id===stationId.value));const available=computed(()=>recipes.value.filter(r=>r.stationKind===selected.value?.kind));
const start=async(r:CraftingRecipeView)=>{if(!stationId.value)return;busy.value=true;error.value='';notice.value='';const n=Math.min(20,Math.max(1,Number(batches.value[r.key]??1)));const x=await rpc<CraftingOrderView>(RpcEvent.CraftingStart,{stationId:stationId.value,recipeKey:r.key,batches:n});busy.value=false;if(x.ok){notice.value='Производство запущено';await load();}else error.value=x.code;};
const collect=async(o:CraftingOrderView)=>{busy.value=true;error.value='';const x=await rpc<CraftingCollectResult>(RpcEvent.CraftingCollect,{orderId:o.id});busy.value=false;if(x.ok){notice.value=`Получено: ${o.outputName} ×${o.outputQuantity}`;await load();}else error.value=x.code;};
const remaining=(o:CraftingOrderView)=>Math.max(0,Math.ceil((new Date(o.readyAt).getTime()-now.value)/1000));
let timer:number|undefined;onMounted(()=>{void load();timer=window.setInterval(()=>now.value=Date.now(),1000);});
</script>
<template><section class="craft"><div class="top"><label>Производственная точка<select v-model="stationId"><option v-for="s in stations" :key="s.id" :value="s.id">{{s.name}} · {{s.kind}}</option></select></label><button @click="load">Обновить</button></div><p class="hint">Запуск и получение доступны только рядом с выбранной станцией. Ресурсы списываются сервером при запуске, готовый заказ переживает перезаход и рестарт.</p><p v-if="error" class="msg error">{{error}}</p><p v-if="notice" class="msg ok">{{notice}}</p><h3>Рецепты</h3><div class="grid"><article v-for="r in available" :key="r.key"><header><div><small>ур. {{r.levelRequired}}</small><b>{{r.name}}</b></div><strong>×{{r.outputQuantity}}</strong></header><p>{{r.ingredients.map(i=>`${i.name} ×${i.quantity}`).join(' · ')}}</p><p>Время: {{r.durationSeconds}} сек / партия</p><div class="row"><input v-model.number="batches[r.key]" type="number" min="1" max="20" placeholder="1"><button :disabled="busy" @click="start(r)">Запустить</button></div></article><p v-if="!available.length" class="empty">Для этой станции рецептов нет.</p></div><h3>Мои заказы</h3><div class="orders"><article v-for="o in orders" :key="o.id"><div><b>{{o.recipeName}}</b><span>{{o.outputName}} ×{{o.outputQuantity}} · {{o.batches}} парт.</span></div><div><span v-if="o.status==='queued'&&remaining(o)>0">{{remaining(o)}} сек</span><button v-else-if="o.status==='queued'" :disabled="busy" @click="collect(o)">Забрать</button><span v-else>{{o.status==='claimed'?'Получено':'Отменено'}}</span></div></article><p v-if="!orders.length" class="empty">Производственных заказов нет.</p></div></section></template>
<style scoped>.craft{display:grid;gap:12px}.top,.row,.orders article,header{display:flex;gap:9px;align-items:center;justify-content:space-between}.top label{display:grid;gap:5px;flex:1;color:var(--e-text-muted);font-size:12px}select,input,button{border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);padding:9px 11px}button{cursor:pointer}.hint,.grid p,.orders span{color:var(--e-text-muted);font-size:12px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.grid article,.orders article{padding:14px;border:1px solid var(--e-border);border-radius:13px;background:var(--e-surface-1)}.grid article{display:grid;gap:8px}.grid small{color:var(--e-accent)}.row input{width:80px}.orders{display:grid;gap:7px}.orders article div{display:flex;flex-direction:column;gap:3px}.msg{padding:9px;border-radius:9px}.error{color:#ff8585;background:#ff555514}.ok{color:#7dde9f;background:#55cc7714}.empty{text-align:center;color:var(--e-text-muted);padding:18px}</style>
