<script setup lang="ts">
import { onMounted,ref } from 'vue';
import { RpcEvent,type CriminalContractView,type CriminalFactionView,type CriminalTerritoryView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
const faction=ref<CriminalFactionView|null>(null),territories=ref<CriminalTerritoryView[]>([]),contracts=ref<CriminalContractView[]>([]),error=ref('');
const load=async()=>{const[f,t,c]=await Promise.all([rpc<CriminalFactionView|null>(RpcEvent.CriminalGet),rpc<CriminalTerritoryView[]>(RpcEvent.CriminalTerritories),rpc<CriminalContractView[]>(RpcEvent.CriminalContracts)]);if(f.ok)faction.value=f.data;else error.value=f.code;if(t.ok)territories.value=t.data;if(c.ok)contracts.value=c.data;};
onMounted(()=>void load());
</script>
<template><section><p v-if="error" class="error">{{error}}</p><div v-if="!faction" class="empty">Вы не состоите в криминальной организации</div><template v-else><div class="hero"><div><small>КРИМИНАЛЬНАЯ ОРГАНИЗАЦИЯ</small><h2>{{faction.name}}</h2><span>{{faction.rankName}} · репутация {{faction.reputation}}</span></div><strong>${{Number(faction.balance).toLocaleString('ru-RU')}}</strong></div><h3>Контракты</h3><div class="contracts"><article v-for="c in contracts" :key="c.id" :class="{done:c.completed}"><div><b>{{c.title}}</b><span>{{c.progress}} / {{c.target}} · ${{Number(c.rewardMoney).toLocaleString('ru-RU')}} · +{{c.rewardReputation}} RP</span></div><em>{{c.completed?'Выполнено':'Прогресс идёт от игровых действий'}}</em></article></div><h3>Территории</h3><div class="territories"><article v-for="t in territories" :key="t.id"><div><b>{{t.name}}</b><span>{{t.ownerName||'Нейтральная'}} · доход ${{Number(t.income).toLocaleString('ru-RU')}}</span></div><small>{{t.center.x.toFixed(0)}}, {{t.center.y.toFixed(0)}} · R {{t.radius.toFixed(0)}} м</small></article></div></template></section></template>
<style scoped>.hero{display:flex;justify-content:space-between;align-items:center;padding:18px;border:1px solid var(--e-border);border-radius:14px;background:var(--e-surface-1)}.hero small{color:var(--e-accent)}.hero h2{margin:4px 0}.hero span,.contracts span,.territories span,.territories small{color:var(--e-text-muted)}.hero strong{font-size:24px}.contracts,.territories{display:grid;gap:8px}.contracts article,.territories article{display:flex;justify-content:space-between;align-items:center;padding:13px;border:1px solid var(--e-border);border-radius:11px;background:var(--e-surface-1)}.contracts article div,.territories article div{display:flex;flex-direction:column;gap:4px}.contracts em{font-style:normal;color:var(--e-text-muted)}.done{opacity:.7}.done em{color:#7ee0a0}.empty{padding:28px;text-align:center;color:var(--e-text-muted)}.error{color:#ff8585}</style>