<script setup lang="ts">
import { onMounted,ref } from 'vue';
import { RpcEvent,type DealershipOfferView,type DealershipPurchaseResult,type DealershipTestDriveResult } from '@eclipse/shared';
import { rpc } from '../core/rpc';
const offers=ref<DealershipOfferView[]>([]),busy=ref(false),error=ref(''),notice=ref('');
const money=(v:string)=>Number(v).toLocaleString('ru-RU',{maximumFractionDigits:0});
const load=async()=>{const r=await rpc<DealershipOfferView[]>(RpcEvent.DealershipOffers);if(r.ok)offers.value=r.data;else error.value=r.code;};
const buy=async(id:string)=>{busy.value=true;error.value='';notice.value='';try{const r=await rpc<DealershipPurchaseResult>(RpcEvent.DealershipBuy,{offerId:id});if(!r.ok){error.value=r.code;return;}notice.value=`Куплен ${r.data.displayName}. VIN ${r.data.vin}`;await load();}finally{busy.value=false;}};
const test=async(id:string)=>{busy.value=true;error.value='';notice.value='';try{const r=await rpc<DealershipTestDriveResult>(RpcEvent.DealershipTestDrive,{offerId:id});if(!r.ok){error.value=r.code;return;}notice.value='Тест-драйв запущен на 5 минут';}finally{busy.value=false;}};
onMounted(()=>void load());
</script>
<template><section class="dealer"><div class="head"><div><small>АВТОСАЛОН</small><h2>Каталог транспорта</h2></div><button @click="load">Обновить</button></div><p v-if="error" class="msg err">{{error}}</p><p v-if="notice" class="msg ok">{{notice}}</p><div class="cars"><article v-for="o in offers" :key="o.id"><div><small>{{o.dealershipName}}</small><h3>{{o.displayName}}</h3><span>{{o.model}} · остаток {{o.stock}}</span></div><strong>${{money(o.price)}}</strong><div class="actions"><button :disabled="busy" @click="test(o.id)">Тест-драйв</button><button :disabled="busy||o.stock<1" @click="buy(o.id)">Купить</button></div></article></div><p class="hint">Покупка и тест-драйв доступны рядом с автосалоном. Купленная машина сразу появляется в вашем гараже.</p></section></template>
<style scoped>.dealer{display:grid;gap:12px;padding-top:18px;border-top:1px solid var(--e-border)}.head{display:flex;justify-content:space-between;align-items:center}.head h2{margin:3px 0}.head small{color:var(--e-accent)}button{padding:9px 12px;border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);cursor:pointer}.cars{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cars article{display:grid;grid-template-columns:1fr auto;gap:10px;padding:15px;border:1px solid var(--e-border);border-radius:12px;background:var(--e-surface-1)}.cars h3{margin:4px 0}.cars span,.hint{color:var(--e-text-muted);font-size:12px}.cars strong{font-size:18px}.actions{grid-column:1/-1;display:flex;gap:8px}.msg{margin:0;padding:9px;border-radius:9px}.err{background:rgba(255,70,70,.1);color:#ff8585}.ok{background:rgba(80,200,120,.1);color:#7dde9f}</style>