<script setup lang="ts">
import { ref } from 'vue';
import { RpcEvent,type DocumentView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
const target=ref(''),doc=ref<DocumentView|null>(null),license=ref<'driver'|'weapon'|'business'|'air'>('driver'),busy=ref(false),error=ref('');
const lookup=async()=>{error.value='';const r=await rpc<DocumentView>(RpcEvent.DocumentGet,{targetCharacterId:Number(target.value)});if(r.ok)doc.value=r.data;else error.value=r.code;};
const issue=async()=>{busy.value=true;const r=await rpc<DocumentView>(RpcEvent.DocumentIssueLicense,{targetCharacterId:Number(target.value),license:license.value});busy.value=false;if(r.ok)doc.value=r.data;else error.value=r.code;};
const revoke=async()=>{busy.value=true;const r=await rpc<DocumentView>(RpcEvent.DocumentRevokeLicense,{targetCharacterId:Number(target.value),license:license.value});busy.value=false;if(r.ok)doc.value=r.data;else error.value=r.code;};
const label=(k:string)=>({driver:'Водительская',weapon:'Оружие',business:'Бизнес',air:'Авиация'} as Record<string,string>)[k]??k;
</script>
<template><section><h2>Документы и лицензии</h2><p v-if="error" class="error">{{error}}</p><div class="toolbar"><input v-model="target" placeholder="Static ID" inputmode="numeric"><button @click="lookup">Открыть документы</button></div><template v-if="doc"><div class="passport"><small>ПАСПОРТ SAN ANDREAS</small><strong>{{doc.passportNumber}}</strong><span>Character ID #{{doc.characterId}}</span><span>Выдан: {{new Date(doc.issuedAt).toLocaleDateString('ru-RU')}}</span></div><h3>Лицензии</h3><div class="licenses"><article v-for="k in ['driver','weapon','business','air']" :key="k"><b>{{label(k)}}</b><span>{{doc.licenses[k]||'Не выдана'}}</span></article></div><div class="actions"><select v-model="license"><option value="driver">Водительская</option><option value="weapon">Оружие</option><option value="business">Бизнес</option><option value="air">Авиация</option></select><button :disabled="busy" @click="issue">Выдать</button><button :disabled="busy" class="danger" @click="revoke">Отозвать</button></div></template></section></template>
<style scoped>.toolbar,.actions{display:flex;gap:8px;margin:15px 0}.toolbar input,select{padding:10px 12px;border:1px solid var(--e-border);border-radius:10px;background:var(--e-surface-1);color:var(--e-text-primary)}button{padding:10px 13px;border:1px solid var(--e-border);border-radius:10px;background:var(--e-surface-2);color:var(--e-text-primary);cursor:pointer}.passport{display:flex;flex-direction:column;gap:6px;padding:18px;border:1px solid var(--e-border);border-radius:14px;background:var(--e-surface-1)}.passport small{color:var(--e-accent)}.passport strong{font-size:22px}.passport span,.licenses span{color:var(--e-text-muted)}.licenses{display:grid;grid-template-columns:1fr 1fr;gap:9px}.licenses article{display:flex;justify-content:space-between;padding:12px;border:1px solid var(--e-border);border-radius:10px}.danger{color:#ff8585}.error{color:#ff8585}</style>