<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';
import { RpcEvent,type FuelStationView,type VehicleRefuelResult,type VehicleView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
import VehicleServicePanel from './VehicleServicePanel.vue';

const stations=ref<FuelStationView[]>([]);const vehicles=ref<VehicleView[]>([]);const stationId=ref('');const vehicleId=ref('');const liters=ref('20');const busy=ref(false);const error=ref('');const notice=ref('');
const spawnedVehicles=computed(()=>vehicles.value.filter(v=>v.spawned));
const station=computed(()=>stations.value.find(s=>s.id===stationId.value)??null);
const money=(v:string)=>Number(v).toLocaleString('ru-RU',{maximumFractionDigits:2});
const load=async()=>{const[s,v]=await Promise.all([rpc<FuelStationView[]>(RpcEvent.FuelStations),rpc<VehicleView[]>(RpcEvent.VehicleUsableList)]);if(s.ok)stations.value=s.data;if(v.ok)vehicles.value=v.data;};
const refuel=async()=>{if(busy.value||!stationId.value||!vehicleId.value)return;busy.value=true;error.value='';notice.value='';try{const r=await rpc<VehicleRefuelResult>(RpcEvent.VehicleRefuel,{stationId:stationId.value,vehicleId:vehicleId.value,liters:Number(liters.value)});if(!r.ok){error.value=r.code;return;}notice.value=`Заправлено ${r.data.liters} л за $${money(r.data.totalCost)}. Топливо: ${r.data.fuel}%`;await load();}finally{busy.value=false;}};
onMounted(()=>void load());
</script>
<template><section class="fuel"><div class="toolbar"><div><small>ТРАНСПОРТНЫЙ СЕРВИС</small><h2>АЗС, ремонт и ключи</h2></div><button @click="load">Обновить</button></div><p v-if="error" class="msg error">{{error}}</p><p v-if="notice" class="msg ok">{{notice}}</p><div class="layout"><div class="stations"><article v-for="s in stations" :key="s.id" :class="{active:stationId===s.id}" @click="stationId=s.id"><div><strong>{{s.name}}</strong><span>{{s.position.x.toFixed(1)}}, {{s.position.y.toFixed(1)}}</span></div><div><b>${{money(s.pricePerLiter)}}/л</b><span>Остаток: {{s.stock}} л</span></div></article><p v-if="!stations.length" class="empty">АЗС не найдены.</p></div><div class="refuel-box"><h3>Заправка</h3><label>Машина<select v-model="vehicleId"><option value="">Выберите заспавненную машину</option><option v-for="v in spawnedVehicles" :key="v.id" :value="v.id">{{v.model}} · {{v.plate??v.vin}} · {{v.fuel}}%</option></select></label><label>АЗС<select v-model="stationId"><option value="">Выберите АЗС</option><option v-for="s in stations" :key="s.id" :value="s.id">{{s.name}} · ${{money(s.pricePerLiter)}}/л</option></select></label><label>Литры<input v-model="liters" inputmode="numeric"></label><div v-if="station" class="estimate">Примерно: ${{money(String(Number(station.pricePerLiter)*Number(liters||0)))}}</div><button :disabled="busy||!vehicleId||!stationId" @click="refuel">Заправить рядом с колонкой</button><small>Игрок и выбранная машина должны находиться рядом с этой АЗС. Максимум бака — 100 л.</small></div></div><VehicleServicePanel/></section></template>
<style scoped>.fuel{display:grid;gap:18px}.toolbar{display:flex;justify-content:space-between;align-items:center}.toolbar small{color:var(--e-accent);letter-spacing:.12em}.toolbar h2{margin:3px 0}.layout{display:grid;grid-template-columns:1.3fr .7fr;gap:14px}.stations{display:grid;gap:8px}.stations article{display:flex;justify-content:space-between;gap:16px;padding:14px;border:1px solid var(--e-border);border-radius:12px;background:var(--e-surface-1);cursor:pointer}.stations article.active{border-color:var(--e-accent);background:var(--e-accent-soft)}.stations article>div{display:flex;flex-direction:column;gap:4px}.stations span,.refuel-box small{color:var(--e-text-muted);font-size:11px}.refuel-box{display:grid;gap:10px;padding:16px;border:1px solid var(--e-border);border-radius:14px;background:var(--e-surface-1)}label{display:grid;gap:5px;color:var(--e-text-muted);font-size:12px}select,input,button{border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);padding:10px}button{cursor:pointer}button:disabled{opacity:.45}.estimate{padding:10px;border-radius:9px;background:var(--e-surface-2)}.msg{padding:9px 12px;border-radius:9px}.error{background:rgba(255,80,80,.1);color:#ff8585}.ok{background:rgba(80,200,120,.1);color:#7dde9f}.empty{text-align:center;color:var(--e-text-muted);padding:25px}</style>
