<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RpcEvent,type BarberApplyResult,type BarberCatalogItem,type CustomizationShopView,type TattooBuyResult,type TattooCatalogItem,type TattooView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
const barbers=ref<BarberCatalogItem[]>([]),tattoos=ref<TattooCatalogItem[]>([]),owned=ref<TattooView[]>([]),shops=ref<CustomizationShopView[]>([]),color=ref(0),highlight=ref(0),busy=ref(false),error=ref('');
const load=async()=>{const[b,t,o,s]=await Promise.all([rpc<BarberCatalogItem[]>(RpcEvent.BarberCatalog),rpc<TattooCatalogItem[]>(RpcEvent.TattooCatalog),rpc<TattooView[]>(RpcEvent.TattooCurrent),rpc<CustomizationShopView[]>(RpcEvent.CustomizationShops)]);if(b.ok)barbers.value=b.data;else error.value=b.code;if(t.ok)tattoos.value=t.data;if(o.ok)owned.value=o.data;if(s.ok)shops.value=s.data;};
const barber=async(item:BarberCatalogItem)=>{if(busy.value)return;busy.value=true;error.value='';const r=await rpc<BarberApplyResult>(RpcEvent.BarberApply,{itemKey:item.key,color:color.value,highlight:highlight.value});busy.value=false;if(!r.ok){error.value=r.code;return;}await load();};
const tattoo=async(item:TattooCatalogItem)=>{if(busy.value||item.owned)return;busy.value=true;error.value='';const r=await rpc<TattooBuyResult>(RpcEvent.TattooBuy,{itemKey:item.key});busy.value=false;if(!r.ok){error.value=r.code;return;}owned.value=r.data.tattoos;await load();};
const money=(v:string)=>Number(v).toLocaleString('ru-RU');onMounted(()=>void load());
</script>
<template><section><p v-if="error" class="error">{{error}}</p><div class="shops"><article v-for="s in shops.filter(x=>x.kind!=='clothing')" :key="s.id"><div><b>{{s.name}}</b><span>{{s.kind==='barber'?'Барбершоп':'Тату-салон'}} · покупка только рядом</span></div><small>{{s.position.x.toFixed(1)}}, {{s.position.y.toFixed(1)}}</small></article></div><div class="controls"><label>Основной цвет <input v-model.number="color" type="number" min="0" max="63"></label><label>Доп. цвет <input v-model.number="highlight" type="number" min="0" max="63"></label></div><h3>Барбершоп</h3><div class="grid"><article v-for="item in barbers" :key="item.key" :class="{selected:item.selected}"><small>{{item.category.toUpperCase()}}</small><b>{{item.name}}</b><span>Стиль {{item.style}}</span><strong>${{money(item.price)}}</strong><button :disabled="busy" @click="barber(item)">{{item.selected?'Изменить цвет':'Применить'}}</button></article></div><h3>Татуировки</h3><div class="grid"><article v-for="item in tattoos" :key="item.key" :class="{selected:item.owned}"><small>{{item.zone.toUpperCase()}}</small><b>{{item.name}}</b><span>{{item.collection}}</span><strong>${{money(item.price)}}</strong><button :disabled="busy||item.owned" @click="tattoo(item)">{{item.owned?'Куплено':'Нанести'}}</button></article></div><p class="owned">Активных татуировок: {{owned.length}}</p></section></template>
<style scoped>.shops,.grid{display:grid;gap:9px}.shops{grid-template-columns:1fr 1fr;margin-bottom:18px}.shops article,.grid article{padding:13px;border:1px solid var(--e-border);border-radius:11px;background:var(--e-surface-1)}.shops article{display:flex;justify-content:space-between}.shops article div,.grid article{display:flex;flex-direction:column;gap:5px}.shops span,.shops small,.grid span,.grid small,.owned{color:var(--e-text-muted)}.controls{display:flex;gap:10px;margin:14px 0}.controls label{display:flex;gap:8px;align-items:center}.controls input{width:70px;padding:8px;background:var(--e-surface-1);border:1px solid var(--e-border);color:var(--e-text-primary)}.grid{grid-template-columns:repeat(3,1fr)}button{padding:9px;border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);cursor:pointer}.selected{border-color:var(--e-accent)!important}.error{color:#ff8585}</style>