<script setup lang="ts">
import { ref } from 'vue';
import { CefEvent } from '@eclipse/shared';
import { onClient } from '../core/bridge';
const visible=ref(false),health=ref(100),armour=ref(0),cash=ref('0'),bank=ref('0'),playerId=ref(-1),voiceActive=ref(false),vehicleVisible=ref(false),speed=ref(0),engine=ref(false),promptVisible=ref(false),promptKey=ref('E'),promptLabel=ref('');
onClient(CefEvent.HudState,p=>{const s=(p??{}) as {visible?:boolean;health?:number;armour?:number;cash?:string;bank?:string;playerId?:number;voiceActive?:boolean;vehicle?:{visible?:boolean;speed?:number;engine?:boolean}};visible.value=s.visible!==false;health.value=Math.round(Number(s.health??100));armour.value=Math.round(Number(s.armour??0));cash.value=String(s.cash??'0');bank.value=String(s.bank??'0');playerId.value=Number(s.playerId??-1);voiceActive.value=s.voiceActive===true;vehicleVisible.value=s.vehicle?.visible===true;speed.value=Math.max(0,Math.round(Number(s.vehicle?.speed??0)));engine.value=s.vehicle?.engine===true;});
onClient(CefEvent.InteractionPrompt,p=>{const s=(p??{}) as {visible?:boolean;key?:string;label?:string};promptVisible.value=s.visible===true;promptKey.value=s.key??'E';promptLabel.value=s.label??'';});
const money=(v:string)=>Number(v).toLocaleString('ru-RU',{maximumFractionDigits:0});
</script>
<template><div v-if="visible" class="hud"><div class="top"><div class="brand">ECLIPSE <b>RP</b></div><div class="status"><span>ID {{playerId}}</span><span :class="{talk:voiceActive}">MIC {{voiceActive?'ON':'OFF'}}</span></div></div><div class="money"><span>НАЛИЧНЫЕ <b>${{money(cash)}}</b></span><span>БАНК <b>${{money(bank)}}</b></span></div><div class="vitals"><div><span>HP</span><i><em :style="{width:health+'%'}"></em></i><b>{{health}}</b></div><div><span>ARM</span><i><em :style="{width:armour+'%'}"></em></i><b>{{armour}}</b></div></div><div v-if="vehicleVisible" class="vehicle"><strong>{{speed}}</strong><span>KM/H</span><small>{{engine?'ENGINE ON':'ENGINE OFF'}}</small></div></div><Transition name="prompt"><div v-if="promptVisible" class="prompt"><kbd>{{promptKey}}</kbd><span>{{promptLabel}}</span></div></Transition></template>
<style scoped>.hud{position:fixed;top:28px;right:30px;width:280px;display:grid;gap:8px;pointer-events:none;color:#fff;text-shadow:0 1px 3px #000}.top{display:flex;justify-content:space-between;align-items:center}.brand{text-align:right;font-weight:900;letter-spacing:.12em;font-size:14px}.brand b{color:var(--e-accent)}.status{display:flex;gap:6px;font-size:9px}.status span{padding:4px 6px;border:1px solid rgba(255,255,255,.15);border-radius:7px;background:rgba(10,12,18,.55)}.status .talk{color:#85ffad}.money{display:flex;justify-content:flex-end;gap:12px}.money span{font-size:9px;color:var(--e-text-muted);display:flex;flex-direction:column;align-items:flex-end}.money b{font-size:13px;color:#fff}.vitals{display:grid;gap:4px;margin-left:auto;width:210px}.vitals>div{display:grid;grid-template-columns:30px 1fr 28px;gap:7px;align-items:center;font-size:10px}.vitals i{height:5px;background:rgba(255,255,255,.18);border-radius:8px;overflow:hidden}.vitals em{display:block;height:100%;background:currentColor;border-radius:8px}.vitals b{text-align:right}.vehicle{margin-left:auto;display:grid;grid-template-columns:auto auto;align-items:end;gap:0 6px;padding:8px 10px;border:1px solid rgba(255,255,255,.15);border-radius:11px;background:rgba(10,12,18,.55)}.vehicle strong{font-size:28px;line-height:1}.vehicle span{font-size:9px;color:var(--e-text-muted)}.vehicle small{grid-column:1/3;margin-top:3px;font-size:8px;color:var(--e-text-muted)}.prompt{position:fixed;left:50%;bottom:92px;transform:translateX(-50%);display:flex;align-items:center;gap:10px;padding:9px 14px;border:1px solid var(--e-border);border-radius:12px;background:rgba(10,12,18,.9);backdrop-filter:blur(8px);color:#fff;pointer-events:none}.prompt kbd{min-width:28px;height:28px;display:grid;place-items:center;border:1px solid var(--e-border);border-radius:7px;background:var(--e-surface-2);font-weight:800}.prompt-enter-active,.prompt-leave-active{transition:.15s}.prompt-enter-from,.prompt-leave-to{opacity:0;transform:translate(-50%,8px)}</style>