<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';
import { RpcEvent,type BusinessView,type MarketplaceListingView,type MarketplaceObjectType,type MarketplacePurchaseResult,type PropertyOwnedView,type VehicleView } from '@eclipse/shared';
import { rpc } from '../core/rpc';

type Mode='market'|'mine'|'create';
const mode=ref<Mode>('market');const listings=ref<MarketplaceListingView[]>([]);const mine=ref<MarketplaceListingView[]>([]);const cars=ref<VehicleView[]>([]);const properties=ref<PropertyOwnedView[]>([]);const businesses=ref<BusinessView[]>([]);const busy=ref(false);const error=ref('');const notice=ref('');
const objectType=ref<MarketplaceObjectType>('vehicle');const objectId=ref('');const price=ref('');
const money=(v:string)=>Number(v).toLocaleString('ru-RU',{maximumFractionDigits:2});
const options=computed(()=>objectType.value==='vehicle'?cars.value.map(x=>({id:x.id,label:`${x.model} · ${x.plate??x.vin}`,blocked:x.spawned||x.impounded})):objectType.value==='property'?properties.value.map(x=>({id:x.id,label:x.name,blocked:false})):businesses.value.map(x=>({id:x.id,label:x.name,blocked:false})));
const load=async()=>{const[l,m,v,p,b]=await Promise.all([rpc<MarketplaceListingView[]>(RpcEvent.MarketList),rpc<MarketplaceListingView[]>(RpcEvent.MarketMine),rpc<VehicleView[]>(RpcEvent.VehicleList),rpc<PropertyOwnedView[]>(RpcEvent.PropertyOwned),rpc<BusinessView[]>(RpcEvent.BusinessOwned)]);if(l.ok)listings.value=l.data;if(m.ok)mine.value=m.data;if(v.ok)cars.value=v.data;if(p.ok)properties.value=p.data;if(b.ok)businesses.value=b.data;};
const run=async<T>(event:string,payload:unknown,msg:string):Promise<T|null>=>{if(busy.value)return null;busy.value=true;error.value='';notice.value='';try{const r=await rpc<T>(event,payload);if(!r.ok){error.value=r.code;return null;}notice.value=msg;return r.data;}finally{busy.value=false;}};
const create=async()=>{if(!objectId.value||!price.value)return;if(await run<MarketplaceListingView>(RpcEvent.MarketCreate,{objectType:objectType.value,objectId:objectId.value,title:'',price:price.value},'Объявление опубликовано')){objectId.value='';price.value='';mode.value='mine';await load();}};
const cancel=async(id:string)=>{if(await run<MarketplaceListingView>(RpcEvent.MarketCancel,{listingId:id},'Объявление снято'))await load();};
const buy=async(id:string)=>{if(await run<MarketplacePurchaseResult>(RpcEvent.MarketBuy,{listingId:id},'Покупка завершена'))await load();};
const typeName=(t:MarketplaceObjectType)=>({vehicle:'Транспорт',property:'Недвижимость',business:'Бизнес'}[t]);
onMounted(()=>void load());
</script>
<template><section class="market"><div class="toolbar"><div><button :class="{active:mode==='market'}" @click="mode='market'">V‑Market</button><button :class="{active:mode==='mine'}" @click="mode='mine'">Мои объявления</button><button :class="{active:mode==='create'}" @click="mode='create'">Продать</button></div><button @click="load">Обновить</button></div><p v-if="error" class="msg error">{{error}}</p><p v-if="notice" class="msg ok">{{notice}}</p><div v-if="mode==='create'" class="create"><h3>Новое объявление</h3><label>Категория<select v-model="objectType" @change="objectId='' "><option value="vehicle">Транспорт</option><option value="property">Недвижимость</option><option value="business">Бизнес</option></select></label><label>Объект<select v-model="objectId"><option value="">Выберите объект</option><option v-for="o in options" :key="o.id" :value="o.id" :disabled="o.blocked">{{o.label}}{{o.blocked?' · сначала уберите в гараж':''}}</option></select></label><label>Цена<input v-model="price" inputmode="decimal" placeholder="Например 500000"></label><button :disabled="busy||!objectId||!price" @click="create">Опубликовать на 7 дней</button><small>Комиссия при успешной продаже: 5%. Название объекта сервер определяет сам.</small></div><div v-else class="grid"><article v-for="l in (mode==='mine'?mine:listings)" :key="l.id"><div class="head"><div><small>{{typeName(l.objectType)}}</small><h3>{{l.title}}</h3></div><strong>${{money(l.price)}}</strong></div><p>До {{new Date(l.expiresAt).toLocaleString('ru-RU')}}</p><div class="actions"><button v-if="mode==='market'&&!l.ownedByMe" :disabled="busy" @click="buy(l.id)">Купить</button><span v-else-if="mode==='market'">Ваше объявление</span><button v-if="mode==='mine'&&l.status==='active'" class="danger" :disabled="busy" @click="cancel(l.id)">Снять</button><span v-if="mode==='mine'&&l.status!=='active'">{{l.status==='sold'?'Продано':'Снято'}}</span></div></article><p v-if="!(mode==='mine'?mine:listings).length" class="empty">Объявлений нет.</p></div></section></template>
<style scoped>.market{display:grid;gap:14px}.toolbar{display:flex;justify-content:space-between}.toolbar>div{display:flex;gap:7px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}article,.create{padding:16px;border:1px solid var(--e-border);border-radius:14px;background:var(--e-surface-1)}.head{display:flex;justify-content:space-between;gap:15px}.head h3{margin:4px 0}.head small{color:var(--e-accent)}p,small,span{color:var(--e-text-muted);font-size:12px}button{border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);padding:9px 12px;cursor:pointer}button.active{border-color:var(--e-accent);background:var(--e-accent-soft)}button:disabled{opacity:.45}.actions{display:flex;gap:8px;align-items:center}.danger{color:#ff8585}.create{max-width:620px;display:grid;gap:10px}.create label{display:grid;gap:5px;color:var(--e-text-muted);font-size:12px}.create select,.create input{border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);padding:10px}.msg{padding:9px 12px;border-radius:9px}.error{background:rgba(255,80,80,.1);color:#ff8585}.ok{background:rgba(80,200,120,.1);color:#7dde9f}.empty{grid-column:1/-1;text-align:center;padding:25px}</style>
