<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RpcEvent,type OrganizationCallView,type OrganizationDutyResult,type OrganizationMemberView,type OrganizationView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
const org=ref<OrganizationView|null>(null);const members=ref<OrganizationMemberView[]>([]);const calls=ref<OrganizationCallView[]>([]);const busy=ref(false);const error=ref('');
const load=async()=>{error.value='';const[o,m]=await Promise.all([rpc<OrganizationView|null>(RpcEvent.OrganizationGet),rpc<OrganizationMemberView[]>(RpcEvent.OrganizationMembers)]);if(o.ok)org.value=o.data;if(m.ok)members.value=m.data;if(org.value?.onDuty){const c=await rpc<OrganizationCallView[]>(RpcEvent.OrganizationCalls);if(c.ok)calls.value=c.data;}};
const duty=async()=>{if(busy.value)return;busy.value=true;try{const r=await rpc<OrganizationDutyResult>(RpcEvent.OrganizationDuty);if(!r.ok){error.value=r.code;return;}await load();}finally{busy.value=false;}};
const assign=async(id:string)=>{const r=await rpc<{assigned:true}>(RpcEvent.OrganizationAssignCall,{callId:id});if(!r.ok){error.value=r.code;return;}await load();};
const close=async(id:string)=>{const r=await rpc<{closed:true}>(RpcEvent.OrganizationCloseCall,{callId:id});if(!r.ok){error.value=r.code;return;}await load();};
onMounted(()=>void load());
</script>
<template><section class="org"><p v-if="error" class="error">{{error}}</p><div v-if="!org" class="empty">Вы не состоите в государственной организации.</div><template v-else><header><div><small>{{org.kind}}</small><h2>{{org.name}}</h2><p>{{org.rankName}} · ранг {{org.rankIndex}}</p></div><button @click="duty">{{org.onDuty?'Завершить дежурство':'Начать дежурство'}}</button></header><h3>Сотрудники</h3><div class="grid"><article v-for="m in members" :key="m.characterId"><b>{{m.name}}</b><span>{{m.rankName}}</span><em :class="{on:m.onDuty}">{{m.onDuty?'На дежурстве':'Не на дежурстве'}}</em></article></div><template v-if="org.onDuty"><h3>Вызовы</h3><div class="calls"><article v-for="c in calls" :key="c.id"><div><b>{{c.kind==='police'?'Вызов полиции':'Вызов EMS'}}</b><p>{{c.message}}</p><small>{{c.position.x.toFixed(1)}}, {{c.position.y.toFixed(1)}} · {{new Date(c.createdAt).toLocaleTimeString('ru-RU')}}</small></div><div><button v-if="c.status==='open'" @click="assign(c.id)">Принять</button><button v-else-if="c.assignedCharacterId" @click="close(c.id)">Закрыть</button></div></article><p v-if="!calls.length" class="empty">Активных вызовов нет.</p></div></template></template></section></template>
<style scoped>.org{display:grid;gap:14px}header{display:flex;justify-content:space-between;align-items:center;padding:16px;border:1px solid var(--e-border);border-radius:14px;background:var(--e-surface-1)}h2,h3,p{margin:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.grid article,.calls article{padding:12px;border:1px solid var(--e-border);border-radius:12px;background:var(--e-surface-1)}.grid article{display:grid;gap:4px}.grid span,.grid em,.calls small{color:var(--e-text-muted);font-size:12px}.grid em.on{color:#7dde9f}.calls{display:grid;gap:10px}.calls article{display:flex;justify-content:space-between;gap:12px}.calls p{margin:5px 0}.empty{text-align:center;color:var(--e-text-muted);padding:20px}.error{color:#ff8585}button{border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);padding:9px 12px;cursor:pointer}small{color:var(--e-accent);text-transform:uppercase}</style>