<script setup lang="ts">
import { ref } from 'vue';import { CefEvent,type InventoryView } from '@eclipse/shared';import { onClient,toClient } from '../core/bridge';
type Mode='search'|'jail';const visible=ref(false),mode=ref<Mode>('search'),inventory=ref<InventoryView|null>(null),minutes=ref(15),reason=ref('Задержание сотрудником LSPD');
onClient(CefEvent.PoliceInteraction,p=>{const x=(p??{}) as {visible?:boolean;mode?:Mode;inventory?:InventoryView};visible.value=x.visible===true;if(x.mode)mode.value=x.mode;if(x.inventory)inventory.value=x.inventory;});
const close=()=>{visible.value=false;toClient(CefEvent.ContextAction,{id:'police-dialog-close'});};
const seize=(itemId:string,max:number)=>{const raw=window.prompt(`Количество для изъятия (1-${max})`,'1');if(raw===null)return;const quantity=Number(raw);if(!Number.isInteger(quantity)||quantity<1||quantity>max)return;toClient(CefEvent.ContextAction,{id:'police-seize',itemId,quantity});};
const jail=()=>{const m=Math.max(1,Math.min(240,Number(minutes.value)||0)),r=reason.value.trim();if(r.length<3)return;toClient(CefEvent.ContextAction,{id:'police-jail-confirm',minutes:m,reason:r});visible.value=false;};
</script>
<template><div v-if="visible" class="shade e-interactive"><section class="panel"><header><div><small>LSPD</small><h2>{{mode==='search'?'Результаты обыска':'Оформление ареста'}}</h2></div><button @click="close">×</button></header><template v-if="mode==='search'"><div v-if="inventory?.items.length" class="items"><article v-for="item in inventory.items" :key="item.id"><div><b>{{item.name}}</b><span>{{item.category}} · ×{{item.quantity}}</span></div><button @click="seize(item.id,item.quantity)">Изъять</button></article></div><p v-else class="empty">При обыске ничего не найдено.</p></template><template v-else><label>Срок, минут<input v-model.number="minutes" type="number" min="1" max="240"></label><label>Причина<textarea v-model="reason" maxlength="220"></textarea></label><button class="primary" @click="jail">Поместить в тюрьму</button></template></section></div></template>
<style scoped>.shade{position:fixed;inset:0;display:grid;place-items:center;background:rgba(2,4,8,.52);backdrop-filter:blur(4px)}.panel{width:min(620px,90vw);max-height:70vh;overflow:auto;padding:22px;border:1px solid var(--e-border);border-radius:18px;background:rgba(10,13,20,.98);box-shadow:0 25px 80px #000a}.panel header{display:flex;justify-content:space-between;align-items:center}.panel header h2{margin:3px 0}.panel header small,.items span{color:var(--e-text-muted)}button{padding:9px 12px;border:1px solid var(--e-border);border-radius:10px;background:var(--e-surface-2);color:#fff;cursor:pointer}.items{display:grid;gap:8px;margin-top:15px}.items article{display:flex;justify-content:space-between;align-items:center;padding:12px;border:1px solid var(--e-border);border-radius:12px}.items article div{display:flex;flex-direction:column;gap:3px}label{display:grid;gap:6px;margin-top:14px;color:var(--e-text-secondary)}input,textarea{padding:10px;border:1px solid var(--e-border);border-radius:10px;background:var(--e-surface-1);color:#fff}textarea{min-height:90px;resize:vertical}.primary{width:100%;margin-top:16px}.empty{padding:25px;text-align:center;color:var(--e-text-muted)}</style>