<script setup lang="ts">
import { ref } from 'vue';
import { RpcEvent,type EmsPatientView,type OrganizationView,type PoliceCitizenView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
const org=ref<OrganizationView|null>(null),citizen=ref<PoliceCitizenView|null>(null),patient=ref<EmsPatientView|null>(null);const target=ref(''),title=ref(''),description=ref(''),amount=ref(''),wanted=ref('0'),busy=ref(false),error=ref('');
const loadOrg=async()=>{const r=await rpc<OrganizationView|null>(RpcEvent.OrganizationGet);if(r.ok)org.value=r.data;};void loadOrg();
const id=()=>Number(target.value);
const lookup=async()=>{error.value='';const event=org.value?.kind==='ems'?RpcEvent.EmsPatient:RpcEvent.PoliceCitizen;const r=await rpc<any>(event,{targetCharacterId:id()});if(!r.ok){error.value=r.code;return;}if(org.value?.kind==='ems')patient.value=r.data;else citizen.value=r.data;};
const addRecord=async(kind:'fine'|'wanted'|'note')=>{busy.value=true;const r=await rpc<PoliceCitizenView>(RpcEvent.PoliceAddRecord,{targetCharacterId:id(),kind,title:title.value,description:description.value,amount:amount.value||undefined,wantedLevel:Number(wanted.value)||undefined});busy.value=false;if(!r.ok){error.value=r.code;return;}citizen.value=r.data;};
const resolve=async(recordId:string)=>{const r=await rpc<PoliceCitizenView>(RpcEvent.PoliceResolveRecord,{recordId});if(r.ok)citizen.value=r.data;else error.value=r.code;};
const treat=async()=>{busy.value=true;const r=await rpc<EmsPatientView>(RpcEvent.EmsTreat,{targetCharacterId:id(),diagnosis:title.value,treatment:description.value,healthAfter:100});busy.value=false;if(r.ok)patient.value=r.data;else error.value=r.code;};
</script>
<template><section><div v-if="!org" class="empty">Вы не состоите в государственной организации</div><template v-else><div class="head"><div><small>{{ org.kind.toUpperCase() }}</small><h2>{{ org.name }} · {{ org.rankName }}</h2></div><span :class="{on:org.onDuty}">{{ org.onDuty?'На дежурстве':'Не на дежурстве' }}</span></div><p v-if="error" class="error">{{ error }}</p><div class="search"><input v-model="target" placeholder="Static ID гражданина" inputmode="numeric"><button @click="lookup">Открыть карточку</button></div><template v-if="org.kind==='police'&&citizen"><div class="cards"><article><small>Гражданин</small><b>{{ citizen.name }} #{{ citizen.characterId }}</b></article><article><small>Розыск</small><b>{{ citizen.wantedLevel }}/5</b></article><article><small>Штрафы</small><b>${{ citizen.activeFineTotal }}</b></article></div><div class="form"><input v-model="title" placeholder="Статья / причина"><input v-model="description" placeholder="Описание"><input v-model="amount" placeholder="Штраф"><input v-model="wanted" placeholder="Розыск 1-5"><button :disabled="busy" @click="addRecord('fine')">Выписать штраф</button><button :disabled="busy" @click="addRecord('wanted')">Объявить розыск</button><button :disabled="busy" @click="addRecord('note')">Добавить заметку</button></div><div class="list"><article v-for="r in citizen.records" :key="r.id"><div><b>{{ r.kind }} · {{ r.title }}</b><small>{{ r.description }} · {{ new Date(r.createdAt).toLocaleString('ru-RU') }}</small></div><button v-if="r.active" @click="resolve(r.id)">Закрыть</button><em v-else>Закрыто</em></article></div></template><template v-else-if="org.kind==='ems'&&patient"><div class="cards"><article><small>Пациент</small><b>{{ patient.name }} #{{ patient.characterId }}</b></article><article><small>HP</small><b>{{ patient.health }}</b></article><article><small>Записей</small><b>{{ patient.history.length }}</b></article></div><div class="form"><input v-model="title" placeholder="Диагноз"><input v-model="description" placeholder="Лечение"><button :disabled="busy" @click="treat">Провести лечение</button></div><div class="list"><article v-for="r in patient.history" :key="r.id"><div><b>{{ r.diagnosis }}</b><small>{{ r.treatment }} · HP {{ r.healthBefore }} → {{ r.healthAfter }}</small></div></article></div></template><div v-else-if="org.kind==='government'" class="empty">Панель Government будет расширена лицензиями и документами.</div></template></section></template>
<style scoped>.head,.search,.form,.list article,.cards{display:flex;gap:10px}.head{justify-content:space-between;align-items:center}.head h2{margin:3px 0}.head small,.cards small,.list small{color:var(--e-text-muted)}.head span{padding:7px 10px;border-radius:10px;background:var(--e-surface-2)}.head span.on{color:#7ee0a0}.search,.form{margin:16px 0;flex-wrap:wrap}.search input,.form input{padding:10px 12px;border:1px solid var(--e-border);border-radius:10px;background:var(--e-surface-1);color:var(--e-text-primary)}button{padding:10px 13px;border:1px solid var(--e-border);border-radius:10px;background:var(--e-surface-2);color:var(--e-text-primary);cursor:pointer}.cards{margin:15px 0}.cards article{flex:1;padding:14px;border:1px solid var(--e-border);border-radius:12px;display:flex;flex-direction:column}.list{display:grid;gap:7px}.list article{justify-content:space-between;align-items:center;padding:12px;border-bottom:1px solid var(--e-border)}.list article div{display:flex;flex-direction:column}.list em{color:var(--e-text-muted)}.error{color:#ff8585}.empty{padding:28px;text-align:center;color:var(--e-text-muted)}</style>