<script setup lang="ts">
import { onMounted,ref } from 'vue';
import { RpcEvent,type VehicleServiceShopView,type VehicleTuningInstallResult,type VehicleTuningOption,type VehicleTuningState,type VehicleView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
const vehicles=ref<VehicleView[]>([]),shops=ref<VehicleServiceShopView[]>([]),options=ref<VehicleTuningOption[]>([]),state=ref<VehicleTuningState|null>(null),vehicleId=ref(''),shopId=ref(''),busy=ref(false),error=ref('');
const load=async()=>{const[v,s,o]=await Promise.all([rpc<VehicleView[]>(RpcEvent.VehicleList),rpc<VehicleServiceShopView[]>(RpcEvent.VehicleServiceShops),rpc<VehicleTuningOption[]>(RpcEvent.VehicleTuningOptions)]);if(v.ok){vehicles.value=v.data;if(!vehicleId.value&&v.data[0])vehicleId.value=v.data[0].id;}if(s.ok){shops.value=s.data;if(!shopId.value&&s.data[0])shopId.value=s.data[0].id;}if(o.ok)options.value=o.data;await loadState();};
const loadState=async()=>{if(!vehicleId.value){state.value=null;return;}const r=await rpc<VehicleTuningState>(RpcEvent.VehicleTuningState,{vehicleId:vehicleId.value});if(r.ok)state.value=r.data;else error.value=r.code;};
const install=async(option:VehicleTuningOption)=>{if(!vehicleId.value||!shopId.value)return;busy.value=true;error.value='';const r=await rpc<VehicleTuningInstallResult>(RpcEvent.VehicleTuningInstall,{vehicleId:vehicleId.value,businessId:shopId.value,optionKey:option.key});busy.value=false;if(r.ok)state.value=r.data.tuning;else error.value=r.code;};
const installed=(o:VehicleTuningOption)=>state.value?.installed[o.category]===o.modIndex;
const price=(o:VehicleTuningOption)=>{const shop=shops.value.find(s=>s.id===shopId.value);return Math.round(Number(o.basePrice)*(shop?.priceMultiplier??1)).toLocaleString('ru-RU');};
onMounted(()=>void load());
</script>
<template><section><p v-if="error" class="error">{{error}}</p><div class="selectors"><label>Автомобиль<select v-model="vehicleId" @change="loadState"><option v-for="v in vehicles" :key="v.id" :value="v.id">{{v.model}} · {{v.plate||v.vin}}</option></select></label><label>Мастерская<select v-model="shopId"><option v-for="s in shops" :key="s.id" :value="s.id">{{s.name}}</option></select></label></div><p class="hint">Для установки автомобиль должен быть доставлен и находиться вместе с вами рядом с выбранной мастерской.</p><div class="grid"><article v-for="o in options" :key="o.key" :class="{installed:installed(o)}"><div><small>{{o.category.toUpperCase()}}</small><b>{{o.name}}</b><span>${{price(o)}}</span></div><button :disabled="busy||installed(o)" @click="install(o)">{{installed(o)?'Установлено':'Установить'}}</button></article></div></section></template>
<style scoped>.selectors{display:grid;grid-template-columns:1fr 1fr;gap:12px}.selectors label{display:flex;flex-direction:column;gap:7px;color:var(--e-text-muted)}select{padding:10px;border:1px solid var(--e-border);border-radius:10px;background:var(--e-surface-1);color:var(--e-text-primary)}.hint{color:var(--e-text-muted);font-size:13px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.grid article{display:flex;justify-content:space-between;align-items:center;padding:14px;border:1px solid var(--e-border);border-radius:12px;background:var(--e-surface-1)}.grid article div{display:flex;flex-direction:column;gap:4px}.grid small,.grid span{color:var(--e-text-muted)}button{padding:9px 12px;border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary)}.installed{opacity:.72}.error{color:#ff8585}</style>