<script setup lang="ts">
import { computed,onBeforeUnmount,onMounted,ref } from 'vue';
import { RpcEvent,type VehicleServiceShopView,type VehicleTuningInstallResult,type VehicleTuningOption,type VehicleTuningPreviewResult,type VehicleTuningState,type VehicleView } from '@eclipse/shared';
import { rpc } from '../core/rpc';
const PREVIEW='eclipse:vehicle:tuningPreview';const vehicles=ref<VehicleView[]>([]),shops=ref<VehicleServiceShopView[]>([]),options=ref<VehicleTuningOption[]>([]),state=ref<VehicleTuningState|null>(null),vehicleId=ref(''),shopId=ref(''),busy=ref(false),error=ref(''),category=ref('all'),previewing=ref(false);
const categories=computed(()=>['all',...Array.from(new Set(options.value.map(x=>x.category)))]);const filtered=computed(()=>category.value==='all'?options.value:options.value.filter(x=>x.category===category.value));
const load=async()=>{const[v,s,o]=await Promise.all([rpc<VehicleView[]>(RpcEvent.VehicleList),rpc<VehicleServiceShopView[]>(RpcEvent.VehicleServiceShops),rpc<VehicleTuningOption[]>(RpcEvent.VehicleTuningOptions)]);if(v.ok){vehicles.value=v.data;if(!vehicleId.value&&v.data[0])vehicleId.value=v.data[0].id;}if(s.ok){shops.value=s.data;if(!shopId.value&&s.data[0])shopId.value=s.data[0].id;}if(o.ok)options.value=o.data;await loadState();};
const loadState=async()=>{await resetPreview();if(!vehicleId.value){state.value=null;return;}const r=await rpc<VehicleTuningState>(RpcEvent.VehicleTuningState,{vehicleId:vehicleId.value});if(r.ok)state.value=r.data;else error.value=r.code;};
const preview=async(o:VehicleTuningOption)=>{if(!vehicleId.value||!shopId.value)return;error.value='';const r=await rpc<VehicleTuningPreviewResult>(PREVIEW,{vehicleId:vehicleId.value,businessId:shopId.value,optionKey:o.key});if(r.ok)previewing.value=true;else error.value=r.code;};
const resetPreview=async()=>{if(!previewing.value||!vehicleId.value||!shopId.value)return;await rpc<VehicleTuningPreviewResult>(PREVIEW,{vehicleId:vehicleId.value,businessId:shopId.value,reset:true});previewing.value=false;};
const install=async(o:VehicleTuningOption)=>{if(!vehicleId.value||!shopId.value)return;busy.value=true;error.value='';const r=await rpc<VehicleTuningInstallResult>(RpcEvent.VehicleTuningInstall,{vehicleId:vehicleId.value,businessId:shopId.value,optionKey:o.key});busy.value=false;if(r.ok){state.value=r.data.tuning;previewing.value=false;}else error.value=r.code;};
const installed=(o:VehicleTuningOption)=>state.value?.installed[o.category]===o.modIndex;const price=(o:VehicleTuningOption)=>{const shop=shops.value.find(s=>s.id===shopId.value);return Math.round(Number(o.basePrice)*(shop?.priceMultiplier??1)).toLocaleString('ru-RU');};const label=(c:string)=>({all:'Все',engine:'Двигатель',brakes:'Тормоза',transmission:'КПП',suspension:'Подвеска',spoiler:'Спойлеры',front_bumper:'Передний бампер',rear_bumper:'Задний бампер',skirts:'Пороги',hood:'Капот',wheels:'Колёса',primary_color:'Основной цвет',secondary_color:'Доп. цвет'} as Record<string,string>)[c]??c;
onMounted(()=>void load());onBeforeUnmount(()=>void resetPreview());
</script>
<template><section><p v-if="error" class="error">{{error}}</p><div class="selectors"><label>Автомобиль<select v-model="vehicleId" @change="loadState"><option v-for="v in vehicles" :key="v.id" :value="v.id">{{v.model}} · {{v.plate||v.vin}}</option></select></label><label>Мастерская<select v-model="shopId" @change="resetPreview"><option v-for="s in shops" :key="s.id" :value="s.id">{{s.name}}</option></select></label></div><p class="hint">Автомобиль должен быть доставлен и стоять рядом с мастерской. «Примерить» меняет вид только временно и не списывает деньги.</p><div class="cats"><button v-for="c in categories" :key="c" :class="{active:category===c}" @click="category=c">{{label(c)}}</button></div><div class="grid"><article v-for="o in filtered" :key="o.key" :class="{installed:installed(o)}"><div><small>{{label(o.category).toUpperCase()}}</small><b>{{o.name}}</b><span>${{price(o)}}</span></div><div class="actions"><button :disabled="busy||installed(o)" @click="preview(o)">Примерить</button><button :disabled="busy||installed(o)" @click="install(o)">{{installed(o)?'Установлено':'Купить'}}</button></div></article></div><div v-if="previewing" class="previewbar"><span>Включён временный preview</span><button @click="resetPreview">Вернуть установленный вид</button></div></section></template>
<style scoped>.selectors{display:grid;grid-template-columns:1fr 1fr;gap:12px}.selectors label{display:flex;flex-direction:column;gap:7px;color:var(--e-text-muted)}select{padding:10px;border:1px solid var(--e-border);border-radius:10px;background:var(--e-surface-1);color:var(--e-text-primary)}.hint{color:var(--e-text-muted);font-size:13px}.cats{display:flex;flex-wrap:wrap;gap:7px;margin:12px 0}.cats button.active{border-color:var(--e-accent);background:var(--e-accent-soft)}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.grid article{display:flex;justify-content:space-between;align-items:center;padding:14px;border:1px solid var(--e-border);border-radius:12px;background:var(--e-surface-1)}.grid article>div:first-child{display:flex;flex-direction:column;gap:4px}.grid small,.grid span{color:var(--e-text-muted)}button{padding:9px 12px;border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);cursor:pointer}.actions{display:flex;gap:6px}.installed{opacity:.72}.error{color:#ff8585}.previewbar{position:sticky;bottom:0;margin-top:12px;padding:10px 12px;border:1px solid var(--e-border);border-radius:11px;background:var(--e-surface-1);display:flex;justify-content:space-between;align-items:center}</style>