<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RpcEvent, type VehicleAccessView, type VehicleRepairQuote, type VehicleRepairResult, type VehicleServiceShopView, type VehicleView } from '@eclipse/shared';
import { rpc } from '../core/rpc';

const owned=ref<VehicleView[]>([]),usable=ref<VehicleView[]>([]),shops=ref<VehicleServiceShopView[]>([]),access=ref<VehicleAccessView[]>([]);
const vehicleId=ref(''),shopId=ref(''),targetCharacterId=ref(''),quote=ref<VehicleRepairQuote|null>(null),busy=ref(false),error=ref(''),notice=ref('');
const load=async()=>{const[o,u,s]=await Promise.all([rpc<VehicleView[]>(RpcEvent.VehicleList),rpc<VehicleView[]>(RpcEvent.VehicleUsableList),rpc<VehicleServiceShopView[]>(RpcEvent.VehicleServiceShops)]);if(o.ok)owned.value=o.data;if(u.ok)usable.value=u.data;if(s.ok)shops.value=s.data;if(!vehicleId.value&&usable.value[0])vehicleId.value=usable.value[0].id;if(!shopId.value&&shops.value[0])shopId.value=shops.value[0].id;};
const refreshAccess=async()=>{access.value=[];if(!vehicleId.value||!owned.value.some(v=>v.id===vehicleId.value))return;const r=await rpc<VehicleAccessView[]>(RpcEvent.VehicleAccessList,{vehicleId:vehicleId.value});if(r.ok)access.value=r.data;};
const getQuote=async()=>{if(!vehicleId.value||!shopId.value)return;busy.value=true;error.value='';notice.value='';try{const r=await rpc<VehicleRepairQuote>(RpcEvent.VehicleRepairQuote,{vehicleId:vehicleId.value,businessId:shopId.value});if(!r.ok){error.value=r.code;return;}quote.value=r.data;}finally{busy.value=false;}};
const repair=async()=>{if(!vehicleId.value||!shopId.value)return;busy.value=true;error.value='';notice.value='';try{const r=await rpc<VehicleRepairResult>(RpcEvent.VehicleRepair,{vehicleId:vehicleId.value,businessId:shopId.value});if(!r.ok){error.value=r.code;return;}notice.value=`Ремонт завершён: $${Number(r.data.paid).toLocaleString('ru-RU')}`;quote.value=null;await load();}finally{busy.value=false;}};
const grant=async()=>{const id=Number(targetCharacterId.value);if(!vehicleId.value||!Number.isInteger(id))return;busy.value=true;error.value='';try{const r=await rpc<VehicleAccessView[]>(RpcEvent.VehicleAccessGrant,{vehicleId:vehicleId.value,characterId:id,accessLevel:'driver'});if(!r.ok){error.value=r.code;return;}access.value=r.data;targetCharacterId.value='';notice.value='Ключ выдан';}finally{busy.value=false;}};
const revoke=async(id:number)=>{busy.value=true;error.value='';try{const r=await rpc<VehicleAccessView[]>(RpcEvent.VehicleAccessRevoke,{vehicleId:vehicleId.value,characterId:id});if(!r.ok){error.value=r.code;return;}access.value=r.data;}finally{busy.value=false;}};
onMounted(()=>void load());
</script>
<template>
<section class="svc">
 <p v-if="error" class="msg err">{{error}}</p><p v-if="notice" class="msg ok">{{notice}}</p>
 <div class="grid">
  <article><small>РЕМОНТ / ТО</small><h3>Сервис транспорта</h3><label>Автомобиль<select v-model="vehicleId" @change="quote=null;refreshAccess()"><option v-for="v in usable" :key="v.id" :value="v.id">{{v.model}} · {{v.plate||v.vin}}</option></select></label><label>Мастерская<select v-model="shopId" @change="quote=null"><option v-for="s in shops" :key="s.id" :value="s.id">{{s.name}} · склад {{s.stock}}</option></select></label><div class="actions"><button :disabled="busy" @click="getQuote">Рассчитать</button><button :disabled="busy||!quote" @click="repair">Оплатить и починить</button></div><div v-if="quote" class="quote"><b>${{Number(quote.total).toLocaleString('ru-RU')}}</b><span>Двигатель: {{quote.engineDamage}} урона · кузов: {{quote.bodyDamage}}</span></div><p class="hint">Машина и игрок должны находиться рядом с выбранной мастерской.</p></article>
  <article><small>КЛЮЧИ И ДОСТУП</small><h3>Передача права управления</h3><p v-if="!owned.some(v=>v.id===vehicleId)" class="hint">Выберите собственный автомобиль: чужими ключами нельзя распоряжаться.</p><template v-else><div class="invite"><input v-model="targetCharacterId" inputmode="numeric" placeholder="Static / Character ID"><button :disabled="busy" @click="grant">Выдать ключ</button></div><button class="refresh" @click="refreshAccess">Обновить список</button><div class="people"><div v-for="a in access" :key="a.characterId"><span><b>{{a.firstName}} {{a.lastName}}</b><small>ID {{a.characterId}} · {{a.accessLevel}}</small></span><button :disabled="busy" @click="revoke(a.characterId)">Забрать</button></div><p v-if="!access.length" class="hint">Дополнительных ключей пока нет.</p></div></template></article>
 </div>
</section>
</template>
<style scoped>
.svc{display:grid;gap:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid>article{padding:18px;border:1px solid var(--e-border);border-radius:14px;background:var(--e-surface-1)}small{color:var(--e-text-muted)}h3{margin:5px 0 16px}label{display:grid;gap:6px;margin:10px 0;color:var(--e-text-secondary);font-size:12px}select,input{width:100%;box-sizing:border-box;padding:10px;border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary)}button{padding:9px 12px;border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary);cursor:pointer}.actions,.invite{display:flex;gap:8px}.invite input{flex:1}.quote{display:flex;justify-content:space-between;align-items:center;margin-top:12px;padding:12px;border:1px solid var(--e-accent);border-radius:10px}.quote b{font-size:20px}.hint{color:var(--e-text-muted);font-size:12px}.people{margin-top:10px}.people>div{display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-bottom:1px solid var(--e-border)}.people span{display:flex;flex-direction:column}.refresh{margin-top:8px}.msg{margin:0;padding:10px;border-radius:9px}.err{background:rgba(255,70,70,.1);color:#ff8585}.ok{background:rgba(80,200,120,.1);color:#7dde9f}
</style>