<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';
import { RpcEvent,type CharacterWeaponView,type WeaponPurchaseResult,type WeaponShopProductView,type WeaponShopView } from '@eclipse/shared';import { rpc } from '../core/rpc';
const shops=ref<WeaponShopView[]>([]),products=ref<WeaponShopProductView[]>([]),owned=ref<CharacterWeaponView[]>([]),shopId=ref(''),busy=ref(false),error=ref(''),notice=ref('');
const visible=computed(()=>products.value.filter(p=>p.shopId===shopId.value));const load=async()=>{const[s,p,w]=await Promise.all([rpc<WeaponShopView[]>(RpcEvent.WeaponShops),rpc<WeaponShopProductView[]>(RpcEvent.WeaponShopProducts),rpc<CharacterWeaponView[]>(RpcEvent.CharacterWeapons)]);if(s.ok){shops.value=s.data;if(!shopId.value&&s.data[0])shopId.value=s.data[0].id;}if(p.ok)products.value=p.data;if(w.ok)owned.value=w.data;};
const buy=async(p:WeaponShopProductView)=>{busy.value=true;error.value='';notice.value='';const r=await rpc<WeaponPurchaseResult>(RpcEvent.WeaponShopBuy,{productId:p.id});busy.value=false;if(r.ok){owned.value=r.data.weapons;notice.value=`Покупка: ${p.name} · $${Number(r.data.paid).toLocaleString('ru-RU')}`;}else error.value=r.code;};
const weaponStatus=(p:WeaponShopProductView)=>p.weaponKey?owned.value.find(w=>w.weaponKey===p.weaponKey):null;
onMounted(()=>void load());
</script>
<template><section class="weapon"><div class="top"><label>Оружейный магазин<select v-model="shopId"><option v-for="s in shops" :key="s.id" :value="s.id">{{s.name}}</option></select></label><button @click="load">Обновить</button></div><p class="hint">Покупка оружия и боеприпасов требует действующей лицензии на оружие. Сервер также проверяет уровень и ваше нахождение внутри магазина.</p><p v-if="error" class="msg error">{{error}}</p><p v-if="notice" class="msg ok">{{notice}}</p><div class="grid"><article v-for="p in visible" :key="p.id"><div><small>{{p.kind}} · ур. {{p.levelRequired}}</small><b>{{p.name}}</b><span v-if="weaponStatus(p)">В наличии: {{weaponStatus(p)?.ammo}} патр.</span><span v-else-if="p.kind==='armour'">Броня +{{p.amount}}</span><span v-else>Количество: {{p.amount}}</span></div><div><strong>${{Number(p.price).toLocaleString('ru-RU')}}</strong><button :disabled="busy" @click="buy(p)">Купить</button></div></article></div><h3>Мой арсенал</h3><div class="owned"><span v-for="w in owned" :key="w.weaponKey">{{w.name}} · {{w.ammo}}/{{w.maxAmmo}}</span><span v-if="!owned.length">Оружия нет</span></div></section></template>
<style scoped>.weapon{display:grid;gap:12px}.top,.grid article{display:flex;justify-content:space-between;gap:10px;align-items:center}.top label{display:grid;gap:5px;flex:1;color:var(--e-text-muted);font-size:12px}select,button{padding:9px 11px;border:1px solid var(--e-border);border-radius:9px;background:var(--e-surface-2);color:var(--e-text-primary)}button{cursor:pointer}.hint,span,small{color:var(--e-text-muted);font-size:12px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.grid article{padding:14px;border:1px solid var(--e-border);border-radius:13px;background:var(--e-surface-1)}.grid article>div{display:flex;flex-direction:column;gap:4px}.grid article>div:last-child{align-items:flex-end}.owned{display:flex;gap:8px;flex-wrap:wrap}.owned span{padding:8px 10px;border:1px solid var(--e-border);border-radius:9px}.msg{padding:9px;border-radius:9px}.error{color:#ff8585;background:#ff555514}.ok{color:#7dde9f;background:#55cc7714}</style>
