import { sql } from 'kysely';
import type { BattlePassTierView,ProgressionKind,ProgressionOverviewView,ProgressionTaskView } from '@eclipse/shared';
import { db } from '../../infra/db';
const SEASON='season-2026-01';
type Def={key:string;kind:ProgressionKind;title:string;description:string;target:number;cash:string;points:number;metric:'jobs_all'|'craft_all'|'casino_all'|'jobs_day'|'casino_day'|'craft_week'|'casino_week'};
const defs:Def[]=[
 {key:'first_steps',kind:'achievement',title:'Трудяга',description:'Завершите 5 рабочих смен.',target:5,cash:'1500',points:100,metric:'jobs_all'},
 {key:'craft_master',kind:'achievement',title:'Мастер производства',description:'Заберите 10 производственных заказов.',target:10,cash:'2500',points:150,metric:'craft_all'},
 {key:'casino_regular',kind:'achievement',title:'Игрок',description:'Сыграйте 20 раундов в казино.',target:20,cash:'1800',points:120,metric:'casino_all'},
 {key:'daily_worker',kind:'daily',title:'Рабочий день',description:'Завершите 2 работы сегодня.',target:2,cash:'700',points:40,metric:'jobs_day'},
 {key:'daily_casino',kind:'daily',title:'Проверить удачу',description:'Сыграйте 5 раундов в казино сегодня.',target:5,cash:'500',points:30,metric:'casino_day'},
 {key:'weekly_craft',kind:'weekly',title:'Производственная неделя',description:'Заберите 5 заказов производства за неделю.',target:5,cash:'2200',points:120,metric:'craft_week'},
 {key:'weekly_casino',kind:'weekly',title:'Завсегдатай казино',description:'Сыграйте 25 раундов за неделю.',target:25,cash:'1800',points:100,metric:'casino_week'},
];
const dayKey=()=>new Date().toISOString().slice(0,10);const weekStart=()=>{const d=new Date(),n=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-n);d.setUTCHours(0,0,0,0);return d;};
const claimKey=(d:Def)=>d.kind==='achievement'?`achievement:${d.key}`:d.kind==='daily'?`daily:${dayKey()}:${d.key}`:`weekly:${weekStart().toISOString().slice(0,10)}:${d.key}`;
const resetAt=(kind:ProgressionKind):string|null=>{if(kind==='achievement')return null;const d=kind==='daily'?new Date(Date.now()+86400000):new Date(weekStart().getTime()+7*86400000);if(kind==='daily')d.setUTCHours(0,0,0,0);return d.toISOString();};
const metric=async(c:number,m:Def['metric']):Promise<number>=>{if(m==='jobs_all'){const r=await sql<{n:number}>`SELECT COALESCE(SUM(completed),0)::int n FROM job_progress WHERE character_id=${c}`.execute(db());return r.rows[0]?.n??0;}if(m==='craft_all'){const r=await sql<{n:number}>`SELECT COUNT(*)::int n FROM crafting_orders WHERE character_id=${c} AND claimed_at IS NOT NULL`.execute(db());return r.rows[0]?.n??0;}if(m==='casino_all'){const r=await sql<{n:number}>`SELECT COUNT(*)::int n FROM casino_game_history WHERE character_id=${c}`.execute(db());return r.rows[0]?.n??0;}if(m==='jobs_day'){const r=await sql<{n:number}>`SELECT COUNT(*)::int n FROM economy_ledger WHERE character_id=${c} AND source LIKE 'job:%' AND created_at>=date_trunc('day',NOW())`.execute(db());return r.rows[0]?.n??0;}if(m==='casino_day'){const r=await sql<{n:number}>`SELECT COUNT(*)::int n FROM casino_game_history WHERE character_id=${c} AND created_at>=date_trunc('day',NOW())`.execute(db());return r.rows[0]?.n??0;}if(m==='craft_week'){const r=await sql<{n:number}>`SELECT COUNT(*)::int n FROM crafting_orders WHERE character_id=${c} AND claimed_at>=date_trunc('week',NOW())`.execute(db());return r.rows[0]?.n??0;}const r=await sql<{n:number}>`SELECT COUNT(*)::int n FROM casino_game_history WHERE character_id=${c} AND created_at>=date_trunc('week',NOW())`.execute(db());return r.rows[0]?.n??0;};
export const overview=async(c:number):Promise<ProgressionOverviewView>=>{const [claims,p]=await Promise.all([sql<{claim_key:string}>`SELECT claim_key FROM progression_claims WHERE character_id=${c}`.execute(db()),sql<{points:number}>`SELECT points FROM progression_points WHERE character_id=${c}`.execute(db())]);const claimed=new Set(claims.rows.map(x=>x.claim_key)),tasks:ProgressionTaskView[]=[];for(const d of defs){const progress=await metric(c,d.metric);tasks.push({key:d.key,kind:d.kind,title:d.title,description:d.description,progress:Math.min(progress,d.target),target:d.target,completed:progress>=d.target,claimed:claimed.has(claimKey(d)),rewardCash:d.cash,rewardPoints:d.points,resetAt:resetAt(d.kind)});}const points=p.rows[0]?.points??0,bp=await sql<{tier:number}>`SELECT tier FROM battle_pass_claims WHERE character_id=${c} AND season_key=${SEASON}`.execute(db()),bpc=new Set(bp.rows.map(x=>x.tier));const battlePass:BattlePassTierView[]=Array.from({length:10},(_,i)=>{const tier=i+1,requiredPoints=tier*100;return{tier,requiredPoints,unlocked:points>=requiredPoints,claimed:bpc.has(tier),rewardCash:String(tier*1000)};});return{points,seasonKey:SEASON,tasks,battlePass};};
export const claimTask=async(c:number,key:string):Promise<ProgressionOverviewView>=>{const d=defs.find(x=>x.key===key);if(!d)throw new Error('PROGRESSION_NOT_FOUND');if(await metric(c,d.metric)<d.target)throw new Error('PROGRESSION_NOT_COMPLETE');const ck=claimKey(d);await db().transaction().execute(async trx=>{const exists=await sql`SELECT 1 FROM progression_claims WHERE character_id=${c} AND claim_key=${ck} FOR UPDATE`.execute(trx);if(exists.rows.length)throw new Error('PROGRESSION_ALREADY_CLAIMED');await sql`INSERT INTO progression_claims(character_id,claim_key) VALUES(${c},${ck})`.execute(trx);await sql`INSERT INTO progression_points(character_id,points) VALUES(${c},${d.points}) ON CONFLICT(character_id) DO UPDATE SET points=progression_points.points+${d.points},updated_at=NOW()`.execute(trx);await sql`UPDATE characters SET cash=cash+${d.cash}::numeric,updated_at=NOW() WHERE id=${c}`.execute(trx);await sql`INSERT INTO economy_ledger(character_id,family_id,source,direction,amount,metadata) VALUES(${c},NULL,'progression_reward','source',${d.cash}::numeric,${JSON.stringify({key:d.key,kind:d.kind})}::jsonb)`.execute(trx);});return overview(c);};
export const claimTier=async(c:number,tier:number):Promise<ProgressionOverviewView>=>{if(!Number.isInteger(tier)||tier<1||tier>10)throw new Error('BATTLE_PASS_TIER_INVALID');const required=tier*100,reward=String(tier*1000);await db().transaction().execute(async trx=>{const p=await sql<{points:number}>`SELECT points FROM progression_points WHERE character_id=${c} FOR UPDATE`.execute(trx);if((p.rows[0]?.points??0)<required)throw new Error('BATTLE_PASS_LOCKED');const done=await sql`SELECT 1 FROM battle_pass_claims WHERE character_id=${c} AND season_key=${SEASON} AND tier=${tier} FOR UPDATE`.execute(trx);if(done.rows.length)throw new Error('BATTLE_PASS_ALREADY_CLAIMED');await sql`INSERT INTO battle_pass_claims(character_id,season_key,tier) VALUES(${c},${SEASON},${tier})`.execute(trx);await sql`UPDATE characters SET cash=cash+${reward}::numeric,updated_at=NOW() WHERE id=${c}`.execute(trx);await sql`INSERT INTO economy_ledger(character_id,family_id,source,direction,amount,metadata) VALUES(${c},NULL,'battle_pass','source',${reward}::numeric,${JSON.stringify({season:SEASON,tier})}::jsonb)`.execute(trx);});return overview(c);};
