import { cef } from './core/browser';
import { installCefBridge } from './core/cefBridge';
import { isInWorld } from './core/world';
import { registerAuthModule } from './modules/auth';
import { registerCharacterModule } from './modules/character';
import { registerSessionModule } from './modules/session';
import { registerEconomyModule } from './modules/economy';
import { registerInventoryModule } from './modules/inventory';
import { registerStoreModule } from './modules/store';
import { registerJobModule } from './modules/jobs';
import { registerFamilyModule } from './modules/family';
import { registerVehicleModule } from './modules/vehicle';
import { registerDealershipModule } from './modules/dealership';
import { registerPropertyModule } from './modules/property';
import { registerBusinessModule } from './modules/business';
import { registerMarketplaceModule } from './modules/marketplace';
import { registerPhoneModule } from './modules/phone';
import { registerQuestModule } from './modules/quests';
import { registerTabletModule } from './modules/tablet';
mp.events.add('render',()=>{if(!isInWorld())mp.game.controls.disableAllControlActions(0);});
const prepareEntryScene=():void=>{const local=mp.players.local;local.freezePosition(true);local.setInvincible(true);mp.game.ui.displayRadar(false);mp.gui.chat.activate(false);mp.gui.chat.show(false);cef.create();cef.screen('auth');cef.focus(true);};
mp.events.add('playerReady',()=>{installCefBridge();registerAuthModule();registerCharacterModule();registerSessionModule();registerEconomyModule();registerInventoryModule();registerStoreModule();registerJobModule();registerFamilyModule();registerVehicleModule();registerDealershipModule();registerPropertyModule();registerBusinessModule();registerMarketplaceModule();registerPhoneModule();registerQuestModule();registerTabletModule();prepareEntryScene();mp.events.callRemote('eclipse:client:ready');});