import { sql } from 'kysely';
import type { VehicleTuningInstallResult,VehicleTuningOption,VehicleTuningPreviewResult,VehicleTuningState } from '@eclipse/shared';
import { db } from '../../infra/db';
import { getSpawnedOwnedVehicleEntity } from './vehicle.service';
import { efficiencyMultiplier } from '../business/businessManagement.service';
interface ShopRow{id:string;markup_percent:number;position_x:string;position_y:string;position_z:string;}
interface VehicleRow{tuning:unknown;}
const OPTIONS:VehicleTuningOption[]=[
 {key:'engine_1',name:'Двигатель Stage 1',category:'engine',modType:11,modIndex:0,basePrice:'18000'},{key:'engine_2',name:'Двигатель Stage 2',category:'engine',modType:11,modIndex:1,basePrice:'36000'},{key:'engine_3',name:'Двигатель Stage 3',category:'engine',modType:11,modIndex:2,basePrice:'72000'},
 {key:'brakes_1',name:'Спортивные тормоза',category:'brakes',modType:12,modIndex:0,basePrice:'12000'},{key:'brakes_2',name:'Гоночные тормоза',category:'brakes',modType:12,modIndex:1,basePrice:'26000'},
 {key:'transmission_1',name:'Спортивная КПП',category:'transmission',modType:13,modIndex:0,basePrice:'15000'},{key:'transmission_2',name:'Гоночная КПП',category:'transmission',modType:13,modIndex:1,basePrice:'32000'},
 {key:'suspension_1',name:'Спортивная подвеска',category:'suspension',modType:15,modIndex:0,basePrice:'11000'},{key:'suspension_2',name:'Низкая подвеска',category:'suspension',modType:15,modIndex:1,basePrice:'24000'},
 {key:'spoiler_1',name:'Спойлер Street',category:'spoiler',modType:0,modIndex:0,basePrice:'9500'},{key:'spoiler_2',name:'Спойлер Sport',category:'spoiler',modType:0,modIndex:1,basePrice:'14500'},
 {key:'front_1',name:'Передний бампер Street',category:'front_bumper',modType:1,modIndex:0,basePrice:'12000'},{key:'front_2',name:'Передний бампер Sport',category:'front_bumper',modType:1,modIndex:1,basePrice:'18500'},
 {key:'rear_1',name:'Задний бампер Street',category:'rear_bumper',modType:2,modIndex:0,basePrice:'11000'},{key:'rear_2',name:'Задний бампер Sport',category:'rear_bumper',modType:2,modIndex:1,basePrice:'17500'},
 {key:'skirts_1',name:'Пороги Street',category:'skirts',modType:3,modIndex:0,basePrice:'9000'},{key:'hood_1',name:'Капот Sport',category:'hood',modType:7,modIndex:0,basePrice:'13500'},
 {key:'wheels_1',name:'Диски Sport',category:'wheels',modType:23,modIndex:0,wheelType:0,basePrice:'16000'},{key:'wheels_2',name:'Диски High End',category:'wheels',modType:23,modIndex:1,wheelType:7,basePrice:'26000'},
 {key:'color_black',name:'Кузов: чёрный',category:'primary_color',modType:-1,modIndex:0,color:0,basePrice:'8000'},{key:'color_white',name:'Кузов: белый',category:'primary_color',modType:-1,modIndex:111,color:111,basePrice:'8000'},{key:'color_red',name:'Кузов: красный',category:'primary_color',modType:-1,modIndex:27,color:27,basePrice:'8000'},{key:'color_blue',name:'Кузов: синий',category:'primary_color',modType:-1,modIndex:64,color:64,basePrice:'8000'},
 {key:'secondary_black',name:'Доп. цвет: чёрный',category:'secondary_color',modType:-2,modIndex:0,color:0,basePrice:'5000'},{key:'secondary_white',name:'Доп. цвет: белый',category:'secondary_color',modType:-2,modIndex:111,color:111,basePrice:'5000'}
];
const dist=(a:{x:number;y:number;z:number},b:{x:number;y:number;z:number})=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);
const parseInstalled=(v:unknown):Record<string,number>=>{if(!v||typeof v!=='object'||Array.isArray(v))return{};const r:Record<string,number>={};for(const[k,x]of Object.entries(v as Record<string,unknown>))if(Number.isInteger(x))r[k]=Number(x);return r;};
const applyOption=(entity:VehicleMp,o:VehicleTuningOption):void=>{const v=entity as VehicleMp&{setMod?:(t:number,i:number)=>void;setWheelType?:(t:number)=>void;setColours?:(p:number,s:number)=>void;getColours?:()=>number[]};if(o.category==='primary_color'||o.category==='secondary_color'){const current=typeof v.getColours==='function'?v.getColours():[0,0];const primary=o.category==='primary_color'?(o.color??o.modIndex):(current[0]??0),secondary=o.category==='secondary_color'?(o.color??o.modIndex):(current[1]??0);if(typeof v.setColours==='function')v.setColours(primary,secondary);return;}if(o.category==='wheels'&&o.wheelType!==undefined&&typeof v.setWheelType==='function')v.setWheelType(o.wheelType);if(typeof v.setMod==='function')v.setMod(o.modType,o.modIndex);};
const restore=(entity:VehicleMp,installed:Record<string,number>):void=>{const types:Record<string,number>={engine:11,brakes:12,transmission:13,suspension:15,spoiler:0,front_bumper:1,rear_bumper:2,skirts:3,hood:7,wheels:23};const v=entity as VehicleMp&{setMod?:(t:number,i:number)=>void;setColours?:(p:number,s:number)=>void};for(const[k,t]of Object.entries(types)){const i=installed[k];if(i!==undefined&&typeof v.setMod==='function')v.setMod(t,i);}if(typeof v.setColours==='function')v.setColours(installed.primary_color??0,installed.secondary_color??0);};
export const listTuningOptions=async():Promise<VehicleTuningOption[]>=>OPTIONS;
export const getTuningState=async(c:number,id:string):Promise<VehicleTuningState>=>{const r=await db().selectFrom('vehicles').select('tuning').where('id','=',id).where('owner_character_id','=',c).executeTakeFirst() as VehicleRow|undefined;if(!r)throw new Error('VEHICLE_NOT_FOUND');return{vehicleId:id,installed:parseInstalled(r.tuning)};};
const shop=async(id:string)=>{const q=await sql<ShopRow>`SELECT id,markup_percent,position_x,position_y,position_z FROM businesses WHERE id=${id}::uuid AND kind='service'`.execute(db());if(!q.rows[0])throw new Error('SERVICE_NOT_FOUND');return q.rows[0];};
const assertNear=async(c:number,p:PlayerMp,vehicleId:string,businessId:string)=>{const entity=getSpawnedOwnedVehicleEntity(c,vehicleId);if(!entity)throw new Error('VEHICLE_NOT_SPAWNED');const s=await shop(businessId),pos={x:Number(s.position_x),y:Number(s.position_y),z:Number(s.position_z)};if(dist(p.position,pos)>12||dist(entity.position,pos)>12)throw new Error('TOO_FAR');return{entity,shop:s};};
export const previewTuning=async(c:number,p:PlayerMp,vehicleId:string,businessId:string,optionKey?:string,reset=false):Promise<VehicleTuningPreviewResult>=>{const{entity}=await assertNear(c,p,vehicleId,businessId);const state=await getTuningState(c,vehicleId);if(reset){restore(entity,state.installed);return{vehicleId,previewing:false};}const option=OPTIONS.find(x=>x.key===optionKey);if(!option)throw new Error('TUNING_OPTION_NOT_FOUND');restore(entity,state.installed);applyOption(entity,option);return{vehicleId,previewing:true,optionKey:option.key};};
export const installTuning=async(c:number,p:PlayerMp,vehicleId:string,businessId:string,optionKey:string):Promise<VehicleTuningInstallResult>=>{const option=OPTIONS.find(x=>x.key===optionKey);if(!option)throw new Error('TUNING_OPTION_NOT_FOUND');const{entity,shop:s}=await assertNear(c,p,vehicleId,businessId);const efficiency=await efficiencyMultiplier(businessId);const total=(Number(option.basePrice)*efficiency*(1+s.markup_percent/100)).toFixed(2);const result=await db().transaction().execute(async trx=>{const vehicle=await trx.selectFrom('vehicles').select('tuning').where('id','=',vehicleId).where('owner_character_id','=',c).forUpdate().executeTakeFirst() as VehicleRow|undefined;if(!vehicle)throw new Error('VEHICLE_NOT_FOUND');const installed=parseInstalled(vehicle.tuning);if(installed[option.category]===option.modIndex)throw new Error('TUNING_ALREADY_INSTALLED');const ch=await trx.selectFrom('characters').select('id').where('id','=',c).where(sql<boolean>`bank>=${total}::numeric`).forUpdate().executeTakeFirst();if(!ch)throw new Error('INSUFFICIENT_FUNDS');installed[option.category]=option.modIndex;if(option.category==='wheels'&&option.wheelType!==undefined)installed.wheel_type=option.wheelType;const updated=await trx.updateTable('characters').set({bank:sql<string>`bank-${total}::numeric`,updated_at:new Date()}).where('id','=',c).returning('bank').executeTakeFirstOrThrow();await trx.updateTable('vehicles').set({tuning:installed,updated_at:new Date()}).where('id','=',vehicleId).execute();await sql`UPDATE businesses SET bank_balance=bank_balance+${total}::numeric,updated_at=NOW() WHERE id=${businessId}::uuid`.execute(trx);await sql`INSERT INTO business_transactions(business_id,character_id,kind,amount,metadata) VALUES(${businessId}::uuid,${c},'vehicle_tuning',${total}::numeric,${JSON.stringify({vehicleId,optionKey})}::jsonb)`.execute(trx);await trx.insertInto('economy_ledger').values({character_id:c,family_id:null,source:'vehicle_tuning',direction:'sink',amount:total,metadata:{businessId,vehicleId,optionKey}}).execute();return{bank:updated.bank,installed};});restore(entity,result.installed);return{tuning:{vehicleId,installed:result.installed},paid:total,bank:result.bank};};
