import { sql } from 'kysely';
import type { VehicleActionView, VehicleView } from '@eclipse/shared';
import { createLogger } from '../../core/logger';
import { db } from '../../infra/db';
import { assertNotActivelyListed } from '../marketplace/marketplace.guard';
import { canUseVehicle } from './access.service';
const log=createLogger('vehicle');
interface VehicleRow{id:string;owner_character_id:number|null;model:string;vin:string;plate:string|null;fuel:string;mileage:string;engine_health:string;body_health:string;locked:boolean;impounded:boolean;insurance_until:Date|null;tuning:unknown;}
interface SpawnedVehicle{entity:VehicleMp;ownerCharacterId:number;actorCharacterId:number;ownerPlayerId:number;}
const spawned=new Map<string,SpawnedVehicle>();const isAlive=(e:SpawnedVehicle|undefined):e is SpawnedVehicle=>e!==undefined&&mp.vehicles.exists(e.entity);const cleanupStale=(id:string)=>{const e=spawned.get(id);if(e&&!mp.vehicles.exists(e.entity))spawned.delete(id);};
const toView=(r:VehicleRow):VehicleView=>{cleanupStale(r.id);return{id:r.id,model:r.model,vin:r.vin,plate:r.plate,fuel:r.fuel,mileage:r.mileage,engineHealth:r.engine_health,bodyHealth:r.body_health,locked:r.locked,impounded:r.impounded,insuranceUntil:r.insurance_until?r.insurance_until.toISOString():null,spawned:spawned.has(r.id)};};
const select=['id','owner_character_id','model','vin','plate','fuel','mileage','engine_health','body_health','locked','impounded','insurance_until','tuning'] as const;
const ownedRow=async(c:number,id:string):Promise<VehicleRow>=>{const r=await db().selectFrom('vehicles').select(select).where('id','=',id).where('owner_character_id','=',c).executeTakeFirst();if(!r)throw new Error('VEHICLE_NOT_FOUND');return r as unknown as VehicleRow;};
const usableRow=async(c:number,id:string):Promise<VehicleRow>=>{if(!await canUseVehicle(c,id))throw new Error('VEHICLE_NOT_FOUND');const r=await db().selectFrom('vehicles').select(select).where('id','=',id).executeTakeFirst();if(!r||r.owner_character_id===null)throw new Error('VEHICLE_NOT_FOUND');return r as unknown as VehicleRow;};
export const listOwnedVehicles=async(c:number):Promise<VehicleView[]>=>{const rows=await db().selectFrom('vehicles').select(select).where('owner_character_id','=',c).orderBy('id').execute() as unknown as VehicleRow[];return rows.map(toView);};
export const listUsableVehicles=async(c:number):Promise<VehicleView[]>=>{const r=await sql<VehicleRow>`SELECT v.id,v.owner_character_id,v.model,v.vin,v.plate,v.fuel,v.mileage,v.engine_health,v.body_health,v.locked,v.impounded,v.insurance_until,v.tuning FROM vehicles v WHERE v.owner_character_id=${c} OR EXISTS(SELECT 1 FROM vehicle_access a WHERE a.vehicle_id=v.id AND a.character_id=${c}) ORDER BY v.id`.execute(db());return r.rows.map(toView);};
const deliveryPosition=(p:PlayerMp):Vector3=>{const h=Number.isFinite(p.heading)?p.heading:0,r=h*Math.PI/180;return new mp.Vector3(p.position.x+Math.sin(r)*4,p.position.y+Math.cos(r)*4,p.position.z);};
const applyTuning=(entity:VehicleMp,value:unknown):void=>{if(!value||typeof value!=='object'||Array.isArray(value))return;const x=value as Record<string,unknown>,v=entity as VehicleMp&{setMod?:(t:number,i:number)=>void;setWheelType?:(t:number)=>void;setColours?:(p:number,s:number)=>void};const types:Record<string,number>={engine:11,brakes:12,transmission:13,suspension:15,spoiler:0,front_bumper:1,rear_bumper:2,skirts:3,hood:7,wheels:23};for(const[k,t]of Object.entries(types)){const i=x[k];if(Number.isInteger(i)&&typeof v.setMod==='function')v.setMod(t,Number(i));}if(Number.isInteger(x.wheel_type)&&typeof v.setWheelType==='function')v.setWheelType(Number(x.wheel_type));if(typeof v.setColours==='function')v.setColours(Number.isInteger(x.primary_color)?Number(x.primary_color):0,Number.isInteger(x.secondary_color)?Number(x.secondary_color):0);};
export const spawnOwnedVehicle=async(c:number,p:PlayerMp,id:string):Promise<VehicleActionView>=>{const row=await usableRow(c,id);if(row.impounded)throw new Error('VEHICLE_IMPOUNDED');await assertNotActivelyListed('vehicle',id);cleanupStale(id);if(isAlive(spawned.get(id)))throw new Error('VEHICLE_ALREADY_SPAWNED');const entity=mp.vehicles.new(mp.joaat(row.model),deliveryPosition(p),{heading:p.heading,numberPlate:(row.plate??'ECLIPSE').slice(0,8),locked:row.locked,engine:false,dimension:p.dimension});const bh=Number(row.body_health);if(Number.isFinite(bh))entity.bodyHealth=bh;applyTuning(entity,row.tuning);spawned.set(id,{entity,ownerCharacterId:row.owner_character_id!,actorCharacterId:c,ownerPlayerId:p.id});return{vehicle:{...toView(row),spawned:true},spawned:true};};
const persistEntity=async(id:string,e:SpawnedVehicle):Promise<void>=>{if(!mp.vehicles.exists(e.entity))return;const p=e.entity.position;await db().updateTable('vehicles').set({position_x:String(p.x.toFixed(3)),position_y:String(p.y.toFixed(3)),position_z:String(p.z.toFixed(3)),heading:String(e.entity.heading.toFixed(2)),dimension:e.entity.dimension,engine_health:String(Math.max(0,e.entity.engineHealth).toFixed(2)),body_health:String(Math.max(0,e.entity.bodyHealth).toFixed(2)),locked:e.entity.locked,updated_at:new Date()}).where('id','=',id).where('owner_character_id','=',e.ownerCharacterId).execute();};
export const storeOwnedVehicle=async(c:number,id:string):Promise<VehicleActionView>=>{const row=await usableRow(c,id);cleanupStale(id);const e=spawned.get(id);if(!e||e.actorCharacterId!==c||!mp.vehicles.exists(e.entity))throw new Error('VEHICLE_NOT_SPAWNED');await persistEntity(id,e);e.entity.destroy();spawned.delete(id);return{vehicle:{...toView(row),spawned:false},spawned:false};};
export const toggleOwnedVehicleLock=async(c:number,id:string):Promise<VehicleView>=>{const row=await usableRow(c,id),locked=!row.locked;await db().updateTable('vehicles').set({locked,updated_at:new Date()}).where('id','=',id).execute();cleanupStale(id);const e=spawned.get(id);if(e&&mp.vehicles.exists(e.entity))e.entity.locked=locked;return{...toView({...row,locked}),locked};};
export const storeVehiclesForPlayer=async(playerId:number):Promise<void>=>{for(const[id,e]of [...spawned.entries()].filter(([,x])=>x.ownerPlayerId===playerId)){try{await persistEntity(id,e);}catch(error){log.error(`не удалось сохранить машину ${id} при выходе`,error);}finally{if(mp.vehicles.exists(e.entity))e.entity.destroy();spawned.delete(id);}}};
export const getSpawnedOwnedVehicleEntity=(c:number,id:string):VehicleMp|null=>{cleanupStale(id);const e=spawned.get(id);if(!e||e.ownerCharacterId!==c||!mp.vehicles.exists(e.entity))return null;return e.entity;};
