import { ServerEvent, SessionState } from '@eclipse/shared';
import { loadConfig } from './core/config';
import { createLogger, setLogLevel } from './core/logger';
import { sessions } from './core/session';
import { connectDatabase, disconnectDatabase } from './infra/db';
import { cache } from './infra/cache';
import { registerAccountModule } from './modules/account/account.controller';
import { registerCharacterModule } from './modules/character/character.controller';
import { registerEconomyModule } from './modules/economy/economy.controller';
import { registerInventoryModule } from './modules/inventory/inventory.controller';
import { registerStoreModule } from './modules/store/store.controller';
import { registerJobModule } from './modules/jobs/job.controller';
import { registerFamilyModule } from './modules/family/family.controller';
import { registerOrganizationModule } from './modules/organization/organization.controller';
import { registerPublicServicesModule } from './modules/publicServices/publicServices.controller';
import { registerDocumentsModule } from './modules/documents/documents.controller';
import { registerCriminalModule } from './modules/criminal/criminal.controller';
import { registerVehicleModule } from './modules/vehicle/vehicle.controller';
import { registerDealershipModule } from './modules/dealership/dealership.controller';
import { registerPropertyModule } from './modules/property/property.controller';
import { registerBusinessModule } from './modules/business/business.controller';
import { registerMarketplaceModule } from './modules/marketplace/marketplace.controller';
import { registerPhoneModule } from './modules/phone/phone.controller';
import { registerQuestModule } from './modules/quests/quest.controller';
import { persist, saveAll, snapshot, startAutosave, stopAutosave } from './modules/character/character.state';
const log=createLogger('boot');let ready=false;let bootFailed=false;
const bootstrap=async():Promise<void>=>{const config=loadConfig();setLogLevel(config.logLevel);log.info(`запуск ${config.serverName} (env=${config.env})`);registerLifecycle();try{await connectDatabase();}catch(error){bootFailed=true;throw error;}cache();registerAccountModule();registerCharacterModule();registerEconomyModule();registerInventoryModule();registerStoreModule();registerJobModule();registerFamilyModule();registerOrganizationModule();registerPublicServicesModule();registerDocumentsModule();registerCriminalModule();registerVehicleModule();registerDealershipModule();registerPropertyModule();registerBusinessModule();registerMarketplaceModule();registerPhoneModule();registerQuestModule();startAutosave(config.world.autosaveSeconds);ready=true;log.info('сервер готов принимать игроков');};
const registerLifecycle=():void=>{mp.events.add('playerJoin',(player:PlayerMp)=>{if(!ready){player.kick(bootFailed?'Технические работы. Сервер временно недоступен, попробуйте позже.':'Сервер ещё запускается. Пожалуйста, переподключитесь через несколько секунд.');return;}const session=sessions.open(player);session.state=SessionState.Authenticating;log.info(`подключился ${player.socialClub} (онлайн: ${sessions.size})`);});mp.events.add('eclipse:client:ready',(player:PlayerMp)=>{const session=sessions.get(player);if(session)player.call(ServerEvent.SessionState,[session.state]);});mp.events.add('playerQuit',(player:PlayerMp,exitType:string,reason:string)=>{const session=sessions.get(player);const state=session?snapshot(player,session):null;sessions.close(player);log.info(`отключился ${player.socialClub} (${exitType}${reason?`: ${reason}`:''})`);if(state)void persist(state).catch((error)=>log.error(`не удалось сохранить персонажа ${state.characterId} при выходе`,error));});};
let shuttingDown=false;const shutdown=async(signal:string):Promise<void>=>{if(shuttingDown)return;shuttingDown=true;log.warn(`получен ${signal}, завершение работы`);ready=false;stopAutosave();try{await saveAll('остановка сервера');}catch(error){log.error('ошибка при сохранении игроков перед остановкой',error);}try{await disconnectDatabase();}catch(error){log.error('ошибка при закрытии соединения с базой',error);}};
process.on('SIGINT',()=>void shutdown('SIGINT'));process.on('SIGTERM',()=>void shutdown('SIGTERM'));process.on('unhandledRejection',(reason)=>log.error('unhandledRejection',reason));bootstrap().catch((error)=>log.error('критический сбой при запуске — сервер не будет работать корректно',error));