import { ErrorCode, RpcTransport, err, type Result } from '@eclipse/shared';
import { createLogger } from './logger';
import type { Session } from './session';
import { sessions } from './session';
const log = createLogger('rpc');
export type RpcHandler<TReq,TRes>=(ctx:RpcContext,payload:TReq)=>Promise<Result<TRes>>|Result<TRes>;
export interface RpcContext{readonly player:PlayerMp;readonly session:Session;}
const registered=new Set<string>();
const replay=new Map<string,{createdAt:number,promise:Promise<Result<unknown>>}>();const REPLAY_TTL=120000,MAX_PAYLOAD=64*1024,MAX_REQUEST_ID=96;
const replayKey=(session:Session,event:string,requestId:string)=>`${session.socialClub}\u0000${event}\u0000${requestId}`;
const sweep=()=>{const cutoff=Date.now()-REPLAY_TTL;for(const[k,v]of replay)if(v.createdAt<cutoff)replay.delete(k);};setInterval(sweep,30000);
const reply=(player:PlayerMp,requestId:string,result:Result<unknown>):void=>{if(!mp.players.exists(player))return;player.call(RpcTransport.Reply,[requestId,JSON.stringify(result)]);};
export const onRpc=<TReq,TRes>(event:string,handler:RpcHandler<TReq,TRes>):void=>{if(registered.has(event))throw new Error(`[rpc] Обработчик события "${event}" уже зарегистрирован. Дубликаты запрещены.`);registered.add(event);mp.events.add(event,(player:PlayerMp,requestId:unknown,payloadJson:unknown)=>{void handleCall(event,handler as RpcHandler<unknown,unknown>,player,requestId,payloadJson);});log.debug(`зарегистрирован обработчик: ${event}`);};
const execute=async(event:string,handler:RpcHandler<unknown,unknown>,player:PlayerMp,session:Session,payload:unknown):Promise<Result<unknown>>=>{try{return await handler({player,session},payload);}catch(error){log.error(`${event}: необработанное исключение (account=${session.accountId??'guest'})`,error);return err(ErrorCode.Internal);}};
const handleCall=async(event:string,handler:RpcHandler<unknown,unknown>,player:PlayerMp,requestId:unknown,payloadJson:unknown):Promise<void>=>{if(typeof requestId!=='string'||requestId.length<1||requestId.length>MAX_REQUEST_ID){log.warn(`${event}: некорректный requestId от ${player?.socialClub??'?'}`);return;}const session=sessions.get(player);if(!session){log.warn(`${event}: RPC без активной сессии`);reply(player,requestId,err(ErrorCode.Unauthorized));return;}if(typeof payloadJson==='string'&&payloadJson.length>MAX_PAYLOAD){reply(player,requestId,err(ErrorCode.Validation,{reason:'payload_too_large'}));return;}let payload:unknown;try{payload=typeof payloadJson==='string'&&payloadJson.length>0?JSON.parse(payloadJson):{};}catch{reply(player,requestId,err(ErrorCode.Validation,{reason:'malformed_payload'}));return;}const key=replayKey(session,event,requestId),existing=replay.get(key);if(existing&&Date.now()-existing.createdAt<=REPLAY_TTL){reply(player,requestId,await existing.promise);return;}const promise=execute(event,handler,player,session,payload);replay.set(key,{createdAt:Date.now(),promise});const result=await promise;reply(player,requestId,result);};
