import type { OrganizationCallView,OrganizationMemberView,OrganizationView } from '@eclipse/shared';
import { db } from '../../infra/db';

const membership=async(characterId:number)=>{const r=await db().selectFrom('organization_members as om').innerJoin('organizations as o','o.id','om.organization_id').innerJoin('organization_ranks as or','or.id','om.rank_id').select(['o.id','o.key','o.name','o.kind','or.name as rank_name','or.rank_index','or.permissions','om.on_duty']).where('om.character_id','=',characterId).executeTakeFirst();return r??null;};
const can=(m:Awaited<ReturnType<typeof membership>>,p:string)=>!!m&&(m.permissions as any)?.all===true||(!!m&&(m.permissions as any)?.[p]===true);
export const getOrganization=async(characterId:number):Promise<OrganizationView|null>=>{const m=await membership(characterId);if(!m)return null;return{id:m.id,key:m.key,name:m.name,kind:m.kind,rankName:m.rank_name,rankIndex:m.rank_index,onDuty:m.on_duty,permissions:m.permissions as Record<string,unknown>};};
export const listMembers=async(characterId:number):Promise<OrganizationMemberView[]>=>{const m=await membership(characterId);if(!m)throw new Error('NOT_IN_ORGANIZATION');const rows=await db().selectFrom('organization_members as om').innerJoin('characters as c','c.id','om.character_id').innerJoin('organization_ranks as or','or.id','om.rank_id').select(['c.id','c.first_name','c.last_name','or.name as rank_name','or.rank_index','om.on_duty','om.joined_at']).where('om.organization_id','=',m.id).orderBy('or.rank_index','desc').execute();return rows.map(r=>({characterId:r.id,name:`${r.first_name} ${r.last_name}`,rankName:r.rank_name,rankIndex:r.rank_index,onDuty:r.on_duty,joinedAt:r.joined_at.toISOString()}));};
export const toggleDuty=async(characterId:number):Promise<boolean>=>{const m=await membership(characterId);if(!m)throw new Error('NOT_IN_ORGANIZATION');if(!can(m,'duty'))throw new Error('NO_PERMISSION');const row=await db().updateTable('organization_members').set({on_duty:!m.on_duty,updated_at:new Date()}).where('organization_id','=',m.id).where('character_id','=',characterId).returning('on_duty').executeTakeFirstOrThrow();await db().insertInto('organization_audit_log').values({organization_id:m.id,actor_character_id:characterId,target_character_id:characterId,action:row.on_duty?'duty_started':'duty_ended',metadata:{}}).execute();return row.on_duty;};
export const listCalls=async(characterId:number):Promise<OrganizationCallView[]>=>{const m=await membership(characterId);if(!m)throw new Error('NOT_IN_ORGANIZATION');if(!m.on_duty)throw new Error('NOT_ON_DUTY');if(!can(m,'calls'))throw new Error('NO_PERMISSION');const rows=await db().selectFrom('organization_calls').selectAll().where('organization_kind','=',m.kind).where('status','in',['open','assigned']).orderBy('created_at','desc').limit(100).execute();return rows.map(r=>({id:r.id,kind:r.organization_kind,callerCharacterId:r.caller_character_id,assignedCharacterId:r.assigned_character_id,status:r.status,message:r.message,position:{x:Number(r.position_x),y:Number(r.position_y),z:Number(r.position_z)},createdAt:r.created_at.toISOString()}));};
export const createCall=async(characterId:number,kind:'police'|'ems',message:string,pos:{x:number;y:number;z:number}):Promise<OrganizationCallView>=>{const text=message.trim().slice(0,220);if(text.length<3)throw new Error('INVALID_MESSAGE');const r=await db().insertInto('organization_calls').values({organization_kind:kind,caller_character_id:characterId,assigned_character_id:null,message:text,position_x:String(pos.x),position_y:String(pos.y),position_z:String(pos.z)}).returningAll().executeTakeFirstOrThrow();return{id:r.id,kind:r.organization_kind,callerCharacterId:r.caller_character_id,assignedCharacterId:r.assigned_character_id,status:r.status,message:r.message,position:{x:Number(r.position_x),y:Number(r.position_y),z:Number(r.position_z)},createdAt:r.created_at.toISOString()};};
export const assignCall=async(characterId:number,callId:string):Promise<void>=>{const m=await membership(characterId);if(!m)throw new Error('NOT_IN_ORGANIZATION');if(!m.on_duty||!can(m,'calls'))throw new Error('NO_PERMISSION');const r=await db().updateTable('organization_calls').set({assigned_character_id:characterId,status:'assigned',updated_at:new Date()}).where('id','=',callId).where('organization_kind','=',m.kind).where('status','=','open').returning('id').executeTakeFirst();if(!r)throw new Error('CALL_UNAVAILABLE');};
export const closeCall=async(characterId:number,callId:string):Promise<void>=>{const m=await membership(characterId);if(!m)throw new Error('NOT_IN_ORGANIZATION');if(!m.on_duty||!can(m,'calls'))throw new Error('NO_PERMISSION');const r=await db().updateTable('organization_calls').set({status:'closed',closed_at:new Date(),updated_at:new Date()}).where('id','=',callId).where('organization_kind','=',m.kind).where('assigned_character_id','=',characterId).where('status','=','assigned').returning('id').executeTakeFirst();if(!r)throw new Error('CALL_UNAVAILABLE');};
