import { sql } from 'kysely';
import type { BusinessPurchaseResult,BusinessRestockResult,BusinessSaleResult,BusinessTreasuryResult,BusinessView } from '@eclipse/shared';
import { db } from '../../infra/db';

interface Row{id:string;kind:string;name:string;owner_character_id:number|null;price:string;cash_balance:string;bank_balance:string;stock:number;stock_capacity:number;wholesale_unit_cost:string;markup_percent:number;position_x:string;position_y:string;position_z:string;}
const MONEY=/^(?:[1-9]\d{0,11})(?:\.\d{1,2})?$/;
const money=(v:string)=>{const s=v.trim();if(!MONEY.test(s))throw new Error('INVALID_AMOUNT');return s;};
const toView=(r:Row,c:number):BusinessView=>({id:r.id,kind:r.kind,name:r.name,price:r.price,owned:r.owner_character_id!==null,ownedByMe:r.owner_character_id===c,cashBalance:r.cash_balance,bankBalance:r.bank_balance,stock:r.stock,stockCapacity:r.stock_capacity,wholesaleUnitCost:r.wholesale_unit_cost,markupPercent:r.markup_percent,position:{x:Number(r.position_x),y:Number(r.position_y),z:Number(r.position_z)}});
const find=async(id:string,trx=db())=>(await sql<Row>`SELECT * FROM businesses WHERE id=${id}::uuid`.execute(trx)).rows[0]??null;
export const catalog=async(c:number)=>(await sql<Row>`SELECT * FROM businesses ORDER BY price,name`.execute(db())).rows.map(r=>toView(r,c));
export const owned=async(c:number)=>(await sql<Row>`SELECT * FROM businesses WHERE owner_character_id=${c} ORDER BY name`.execute(db())).rows.map(r=>toView(r,c));
export const buy=async(c:number,id:string):Promise<BusinessPurchaseResult>=>db().transaction().execute(async trx=>{const rows=await sql<Row>`SELECT * FROM businesses WHERE id=${id}::uuid FOR UPDATE`.execute(trx);const b=rows.rows[0];if(!b)throw new Error('BUSINESS_NOT_FOUND');if(b.owner_character_id!==null)throw new Error('BUSINESS_OWNED');const ch=await trx.selectFrom('characters').select('id').where('id','=',c).where(sql<boolean>`bank>=${b.price}::numeric`).forUpdate().executeTakeFirst();if(!ch)throw new Error('INSUFFICIENT_FUNDS');const u=await trx.updateTable('characters').set({bank:sql<string>`bank-${b.price}::numeric`,updated_at:new Date()}).where('id','=',c).returning('bank').executeTakeFirstOrThrow();await sql`UPDATE businesses SET owner_character_id=${c},updated_at=NOW() WHERE id=${id}::uuid`.execute(trx);await trx.insertInto('economy_ledger').values({character_id:c,family_id:null,source:'business_purchase',direction:'sink',amount:b.price,metadata:{businessId:id}}).execute();return{business:toView({...b,owner_character_id:c},c),bank:u.bank};});
export const sell=async(c:number,id:string):Promise<BusinessSaleResult>=>db().transaction().execute(async trx=>{const rows=await sql<Row>`SELECT * FROM businesses WHERE id=${id}::uuid FOR UPDATE`.execute(trx);const b=rows.rows[0];if(!b||b.owner_character_id!==c)throw new Error('BUSINESS_NOT_OWNED');const listed=await sql`SELECT id FROM marketplace_listings WHERE object_type='business' AND object_id=${id}::uuid AND status='active' AND expires_at>NOW() FOR UPDATE`.execute(trx);if(listed.rows.length)throw new Error('OBJECT_LISTED');const rr=await sql<{refund:string}>`SELECT ROUND(${b.price}::numeric*.65,2)::text refund`.execute(trx);const refund=rr.rows[0]!.refund;await sql`UPDATE businesses SET owner_character_id=NULL,cash_balance=0,bank_balance=0,updated_at=NOW() WHERE id=${id}::uuid`.execute(trx);const u=await trx.updateTable('characters').set({bank:sql<string>`bank+${refund}::numeric`,updated_at:new Date()}).where('id','=',c).returning('bank').executeTakeFirstOrThrow();await trx.insertInto('economy_ledger').values({character_id:c,family_id:null,source:'business_sale_state',direction:'source',amount:refund,metadata:{businessId:id}}).execute();return{businessId:id,refund,bank:u.bank};});
export const deposit=async(c:number,id:string,a:string):Promise<BusinessTreasuryResult>=>move(c,id,money(a),'deposit');
export const withdraw=async(c:number,id:string,a:string):Promise<BusinessTreasuryResult>=>move(c,id,money(a),'withdraw');
const move=async(c:number,id:string,a:string,kind:'deposit'|'withdraw'):Promise<BusinessTreasuryResult>=>db().transaction().execute(async trx=>{const rows=await sql<Row>`SELECT * FROM businesses WHERE id=${id}::uuid FOR UPDATE`.execute(trx);const b=rows.rows[0];if(!b||b.owner_character_id!==c)throw new Error('BUSINESS_NOT_OWNED');if(kind==='deposit'){const ch=await trx.selectFrom('characters').select('id').where('id','=',c).where(sql<boolean>`bank>=${a}::numeric`).forUpdate().executeTakeFirst();if(!ch)throw new Error('INSUFFICIENT_FUNDS');await trx.updateTable('characters').set({bank:sql<string>`bank-${a}::numeric`,updated_at:new Date()}).where('id','=',c).execute();await sql`UPDATE businesses SET bank_balance=bank_balance+${a}::numeric,updated_at=NOW() WHERE id=${id}::uuid`.execute(trx);}else{const enough=await sql`SELECT id FROM businesses WHERE id=${id}::uuid AND bank_balance>=${a}::numeric`.execute(trx);if(!enough.rows.length)throw new Error('INSUFFICIENT_FUNDS');await sql`UPDATE businesses SET bank_balance=bank_balance-${a}::numeric,updated_at=NOW() WHERE id=${id}::uuid`.execute(trx);await trx.updateTable('characters').set({bank:sql<string>`bank+${a}::numeric`,updated_at:new Date()}).where('id','=',c).execute();}await sql`INSERT INTO business_transactions(business_id,character_id,kind,amount) VALUES(${id}::uuid,${c},${kind},${a}::numeric)`.execute(trx);const updated=await find(id,trx);const ch=await trx.selectFrom('characters').select('bank').where('id','=',c).executeTakeFirstOrThrow();return{business:toView(updated!,c),characterBank:ch.bank};});
export const restock=async(c:number,id:string,qty:number):Promise<BusinessRestockResult>=>db().transaction().execute(async trx=>{if(!Number.isInteger(qty)||qty<1||qty>1000)throw new Error('INVALID_QUANTITY');const rows=await sql<Row>`SELECT * FROM businesses WHERE id=${id}::uuid FOR UPDATE`.execute(trx);const b=rows.rows[0];if(!b||b.owner_character_id!==c)throw new Error('BUSINESS_NOT_OWNED');if(b.stock+qty>b.stock_capacity)throw new Error('STOCK_CAPACITY');const cost=(Number(b.wholesale_unit_cost)*qty).toFixed(2);if(Number(b.bank_balance)<Number(cost))throw new Error('INSUFFICIENT_FUNDS');await sql`UPDATE businesses SET bank_balance=bank_balance-${cost}::numeric,stock=stock+${qty},updated_at=NOW() WHERE id=${id}::uuid`.execute(trx);await sql`INSERT INTO business_transactions(business_id,character_id,kind,amount,metadata) VALUES(${id}::uuid,${c},'restock',${cost}::numeric,${JSON.stringify({qty})}::jsonb)`.execute(trx);const u=await find(id,trx);return{business:toView(u!,c),totalCost:cost};});
export const setMarkup=async(c:number,id:string,p:number):Promise<BusinessView>=>{if(!Number.isInteger(p)||p<0||p>300)throw new Error('INVALID_MARKUP');const r=await sql<Row>`UPDATE businesses SET markup_percent=${p},updated_at=NOW() WHERE id=${id}::uuid AND owner_character_id=${c} RETURNING *`.execute(db());if(!r.rows[0])throw new Error('BUSINESS_NOT_OWNED');return toView(r.rows[0],c);};