import { sql } from 'kysely';
import type { InventoryView,PropertyFurnitureView,PropertyGarageView,PropertyOwnedView } from '@eclipse/shared';
import { db } from '../../infra/db';
import { getSpawnedOwnedVehicleEntity,spawnOwnedVehicle } from '../vehicle/vehicle.service';

type AccessRow={id:string;kind:'house'|'apartment';name:string;price:string;owner_character_id:number|null;exterior_x:string;exterior_y:string;exterior_z:string;exterior_heading:string;exterior_dimension:number;interior_x:string;interior_y:string;interior_z:string;interior_heading:string;instance_dimension:number;tax_rate:string;tax_paid_until:Date|null;rent_price:string|null;rent_enabled:boolean;garage_slots:number;tenant_character_id:number|null;rent_paid_until:Date|null;};
const columns=sql<AccessRow>`SELECT p.id,p.kind,p.name,p.price,p.owner_character_id,p.exterior_x,p.exterior_y,p.exterior_z,p.exterior_heading,p.exterior_dimension,p.interior_x,p.interior_y,p.interior_z,p.interior_heading,p.instance_dimension,p.tax_rate,p.tax_paid_until,p.rent_price,p.rent_enabled,p.garage_slots,t.tenant_character_id,t.rent_paid_until FROM properties p LEFT JOIN property_tenants t ON t.property_id=p.id`;
const point=(x:string,y:string,z:string,h:string,d:number)=>({x:Number(x),y:Number(y),z:Number(z),heading:Number(h),dimension:d});
const distance=(a:{x:number;y:number;z:number},b:{x:number;y:number;z:number})=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);
const row=async(id:string):Promise<AccessRow>=>{const q=await sql<AccessRow>`SELECT p.id,p.kind,p.name,p.price,p.owner_character_id,p.exterior_x,p.exterior_y,p.exterior_z,p.exterior_heading,p.exterior_dimension,p.interior_x,p.interior_y,p.interior_z,p.interior_heading,p.instance_dimension,p.tax_rate,p.tax_paid_until,p.rent_price,p.rent_enabled,p.garage_slots,t.tenant_character_id,t.rent_paid_until FROM properties p LEFT JOIN property_tenants t ON t.property_id=p.id WHERE p.id=${id}::uuid`.execute(db());if(!q.rows[0])throw new Error('PROPERTY_NOT_FOUND');return q.rows[0];};
const activeTenant=(r:AccessRow,c:number)=>r.tenant_character_id===c&&!!r.rent_paid_until&&r.rent_paid_until.getTime()>Date.now();
const owner=(r:AccessRow,c:number)=>{if(r.owner_character_id!==c)throw new Error('PROPERTY_NOT_OWNED');};
const accessible=(r:AccessRow,c:number)=>{if(r.owner_character_id!==c&&!activeTenant(r,c))throw new Error('PROPERTY_ACCESS_DENIED');};
const view=(r:AccessRow,c:number):PropertyOwnedView=>({id:r.id,kind:r.kind,name:r.name,price:r.price,owned:r.owner_character_id!==null,ownedByMe:r.owner_character_id===c,exterior:point(r.exterior_x,r.exterior_y,r.exterior_z,r.exterior_heading,r.exterior_dimension),interior:point(r.interior_x,r.interior_y,r.interior_z,r.interior_heading,r.instance_dimension),rentEnabled:r.rent_enabled,rentPrice:r.rent_price,taxRate:r.tax_rate,taxPaidUntil:r.tax_paid_until?.toISOString()??null,garageSlots:r.garage_slots,tenantCharacterId:r.tenant_character_id,rentPaidUntil:r.rent_paid_until?.toISOString()??null});
export const getAccessibleProperty=async(c:number,id:string):Promise<PropertyOwnedView>=>{const r=await row(id);accessible(r,c);return view(r,c);};

const money=(v:string)=>/^(?:0|[1-9]\d{0,11})(?:\.\d{1,2})?$/.test(v)&&Number(v)>0?v:null;
export const configureRent=async(c:number,id:string,enabled:boolean,rawPrice:string):Promise<PropertyOwnedView>=>{const price=money(rawPrice);if(enabled&&!price)throw new Error('INVALID_AMOUNT');const r=await row(id);owner(r,c);await sql`UPDATE properties SET rent_enabled=${enabled},rent_price=${enabled?price:null}::numeric,updated_at=NOW() WHERE id=${id}::uuid`.execute(db());return view(await row(id),c);};
export const rentProperty=async(c:number,id:string,days:number):Promise<PropertyOwnedView>=>{if(!Number.isInteger(days)||days<1||days>30)throw new Error('INVALID_DAYS');await db().transaction().execute(async trx=>{const q=await sql<AccessRow>`SELECT p.id,p.kind,p.name,p.price,p.owner_character_id,p.exterior_x,p.exterior_y,p.exterior_z,p.exterior_heading,p.exterior_dimension,p.interior_x,p.interior_y,p.interior_z,p.interior_heading,p.instance_dimension,p.tax_rate,p.tax_paid_until,p.rent_price,p.rent_enabled,p.garage_slots,t.tenant_character_id,t.rent_paid_until FROM properties p LEFT JOIN property_tenants t ON t.property_id=p.id WHERE p.id=${id}::uuid FOR UPDATE OF p`.execute(trx);const p=q.rows[0];if(!p)throw new Error('PROPERTY_NOT_FOUND');if(p.owner_character_id===null||p.owner_character_id===c||!p.rent_enabled||!p.rent_price)throw new Error('RENT_UNAVAILABLE');if(p.tenant_character_id!==null&&p.tenant_character_id!==c&&p.rent_paid_until&&p.rent_paid_until.getTime()>Date.now())throw new Error('PROPERTY_ALREADY_RENTED');const total=(Number(p.rent_price)*days).toFixed(2);const ch=await trx.selectFrom('characters').select('id').where('id','=',c).where(sql<boolean>`bank>=${total}::numeric`).forUpdate().executeTakeFirst();if(!ch)throw new Error('INSUFFICIENT_FUNDS');const renter=await trx.updateTable('characters').set({bank:sql<string>`bank-${total}::numeric`,updated_at:new Date()}).where('id','=',c).returning('bank').executeTakeFirstOrThrow();const landlord=await trx.updateTable('characters').set({bank:sql<string>`bank+${total}::numeric`,updated_at:new Date()}).where('id','=',p.owner_character_id).returning('bank').executeTakeFirstOrThrow();await sql`INSERT INTO property_tenants(property_id,tenant_character_id,rent_paid_until) VALUES(${id}::uuid,${c},NOW()+(${days}||' days')::interval) ON CONFLICT(property_id) DO UPDATE SET tenant_character_id=EXCLUDED.tenant_character_id,rent_paid_until=EXCLUDED.rent_paid_until,updated_at=NOW()`.execute(trx);await trx.insertInto('bank_transactions').values({character_id:c,counterparty_id:p.owner_character_id,kind:'property_rent',amount:total,balance_after:renter.bank,description:`Аренда недвижимости: ${p.name}`}).execute();await trx.insertInto('bank_transactions').values({character_id:p.owner_character_id,counterparty_id:c,kind:'property_rent_income',amount:total,balance_after:landlord.bank,description:`Доход от аренды: ${p.name}`}).execute();await trx.insertInto('economy_ledger').values({character_id:c,family_id:null,source:'property_rent',direction:'move',amount:total,metadata:{propertyId:id,days,landlord:p.owner_character_id}}).execute();});return view(await row(id),c);};
export const payTax=async(c:number,id:string,days:number):Promise<PropertyOwnedView>=>{if(!Number.isInteger(days)||days<1||days>30)throw new Error('INVALID_DAYS');await db().transaction().execute(async trx=>{const q=await sql<{owner_character_id:number|null;tax_rate:string;tax_paid_until:Date|null;name:string}>`SELECT owner_character_id,tax_rate,tax_paid_until,name FROM properties WHERE id=${id}::uuid FOR UPDATE`.execute(trx);const p=q.rows[0];if(!p||p.owner_character_id!==c)throw new Error('PROPERTY_NOT_OWNED');const total=(Number(p.tax_rate)*days).toFixed(2);const ch=await trx.selectFrom('characters').select('id').where('id','=',c).where(sql<boolean>`bank>=${total}::numeric`).forUpdate().executeTakeFirst();if(!ch)throw new Error('INSUFFICIENT_FUNDS');const u=await trx.updateTable('characters').set({bank:sql<string>`bank-${total}::numeric`,updated_at:new Date()}).where('id','=',c).returning('bank').executeTakeFirstOrThrow();await sql`UPDATE properties SET tax_paid_until=GREATEST(COALESCE(tax_paid_until,NOW()),NOW())+(${days}||' days')::interval,updated_at=NOW() WHERE id=${id}::uuid`.execute(trx);await trx.insertInto('bank_transactions').values({character_id:c,counterparty_id:null,kind:'property_tax',amount:total,balance_after:u.bank,description:`Налог на недвижимость: ${p.name}`}).execute();await trx.insertInto('economy_ledger').values({character_id:c,family_id:null,source:'property_tax',direction:'sink',amount:total,metadata:{propertyId:id,days}}).execute();});return view(await row(id),c);};

const inventoryId=async(propertyId:string):Promise<string>=>{const q=await sql<{id:string}>`SELECT i.id::text id FROM property_storage_owners o JOIN inventories i ON i.owner_type='property' AND i.owner_id=o.storage_owner_id WHERE o.property_id=${propertyId}::uuid`.execute(db());if(!q.rows[0])throw new Error('INVENTORY_NOT_FOUND');return q.rows[0].id;};
const invView=async(id:string):Promise<InventoryView>=>{const h=await sql<{capacity_weight:string;slots:number}>`SELECT capacity_weight::text,slots FROM inventories WHERE id=${id}::bigint`.execute(db());const head=h.rows[0];if(!head)throw new Error('INVENTORY_NOT_FOUND');const q=await sql<any>`SELECT ii.id::text,ii.item_key,ii.slot,ii.quantity,ii.metadata,d.name,d.category,d.weight::text,d.stack_size FROM inventory_items ii JOIN item_definitions d ON d.key=ii.item_key WHERE ii.inventory_id=${id}::bigint ORDER BY ii.slot`.execute(db());const used=q.rows.reduce((s:number,x:any)=>s+Number(x.weight)*Number(x.quantity),0);return{inventoryId:id,capacityWeight:head.capacity_weight,usedWeight:used.toFixed(3),slots:head.slots,items:q.rows.map((x:any)=>({id:x.id,itemKey:x.item_key,name:x.name,category:x.category,slot:x.slot,quantity:x.quantity,weightEach:x.weight,stackSize:x.stack_size,metadata:x.metadata}))};};
export const storage=async(c:number,id:string):Promise<InventoryView>=>{accessible(await row(id),c);return invView(await inventoryId(id));};
export const storageTransfer=async(c:number,id:string,itemId:string,qty:number,direction:'deposit'|'withdraw'):Promise<InventoryView>=>{if(!/^\d+$/.test(itemId)||!Number.isInteger(qty)||qty<=0)throw new Error('INVALID_QUANTITY');accessible(await row(id),c);const propInv=await inventoryId(id);const cq=await sql<{id:string}>`SELECT id::text FROM inventories WHERE owner_type='character' AND owner_id=${c}`.execute(db());const charInv=cq.rows[0]?.id;if(!charInv)throw new Error('INVENTORY_NOT_FOUND');const from=direction==='deposit'?charInv:propInv,to=direction==='deposit'?propInv:charInv;await db().transaction().execute(async trx=>{const iq=await sql<any>`SELECT ii.id::text,ii.item_key,ii.quantity,ii.metadata,d.weight::text FROM inventory_items ii JOIN item_definitions d ON d.key=ii.item_key WHERE ii.id=${itemId}::bigint AND ii.inventory_id=${from}::bigint FOR UPDATE`.execute(trx);const item=iq.rows[0];if(!item||item.quantity<qty)throw new Error('INVALID_QUANTITY');const cap=await sql<{capacity:string;used:string}>`SELECT i.capacity_weight::text capacity,COALESCE(SUM(d.weight*ii.quantity),0)::text used FROM inventories i LEFT JOIN inventory_items ii ON ii.inventory_id=i.id LEFT JOIN item_definitions d ON d.key=ii.item_key WHERE i.id=${to}::bigint GROUP BY i.id`.execute(trx);const ccap=cap.rows[0];if(!ccap||Number(ccap.used)+Number(item.weight)*qty>Number(ccap.capacity))throw new Error('INVENTORY_FULL');const sq=await sql<{slot:number}>`SELECT s slot FROM generate_series(0,(SELECT slots-1 FROM inventories WHERE id=${to}::bigint)) s WHERE NOT EXISTS(SELECT 1 FROM inventory_items WHERE inventory_id=${to}::bigint AND slot=s) LIMIT 1`.execute(trx);const slot=sq.rows[0]?.slot;if(slot===undefined)throw new Error('INVENTORY_FULL');if(item.quantity===qty)await sql`UPDATE inventory_items SET inventory_id=${to}::bigint,slot=${slot},updated_at=NOW() WHERE id=${itemId}::bigint`.execute(trx);else{await sql`UPDATE inventory_items SET quantity=quantity-${qty},updated_at=NOW() WHERE id=${itemId}::bigint`.execute(trx);await sql`INSERT INTO inventory_items(inventory_id,item_key,slot,quantity,metadata) VALUES(${to}::bigint,${item.item_key},${slot},${qty},${JSON.stringify(item.metadata)}::jsonb)`.execute(trx);}});return storage(c,id);};

export const garage=async(c:number,id:string):Promise<PropertyGarageView>=>{const r=await row(id);accessible(r,c);const q=await sql<{vehicle_id:string}>`SELECT vehicle_id::text FROM property_garage_vehicles WHERE property_id=${id}::uuid ORDER BY stored_at`.execute(db());return{propertyId:id,slots:r.garage_slots,vehicleIds:q.rows.map(x=>x.vehicle_id)};};
export const garageStore=async(c:number,p:PlayerMp,id:string,vehicleId:string):Promise<PropertyGarageView>=>{if(!/^\d+$/.test(vehicleId))throw new Error('VEHICLE_NOT_FOUND');const r=await row(id);accessible(r,c);const ext=point(r.exterior_x,r.exterior_y,r.exterior_z,r.exterior_heading,r.exterior_dimension);if(p.dimension!==ext.dimension||distance(p.position,ext)>10)throw new Error('PROPERTY_TOO_FAR');const e=getSpawnedOwnedVehicleEntity(c,vehicleId);if(!e||distance(e.position,ext)>15)throw new Error('VEHICLE_NOT_NEAR_PROPERTY');const count=await sql<{n:string}>`SELECT COUNT(*)::text n FROM property_garage_vehicles WHERE property_id=${id}::uuid`.execute(db());if(Number(count.rows[0]?.n??0)>=r.garage_slots)throw new Error('GARAGE_FULL');await sql`INSERT INTO property_garage_vehicles(property_id,vehicle_id) VALUES(${id}::uuid,${vehicleId}::bigint) ON CONFLICT(vehicle_id) DO NOTHING`.execute(db());if(mp.vehicles.exists(e))e.destroy();return garage(c,id);};
export const garageRelease=async(c:number,p:PlayerMp,id:string,vehicleId:string):Promise<PropertyGarageView>=>{const r=await row(id);accessible(r,c);const ext=point(r.exterior_x,r.exterior_y,r.exterior_z,r.exterior_heading,r.exterior_dimension);if(p.dimension!==ext.dimension||distance(p.position,ext)>10)throw new Error('PROPERTY_TOO_FAR');const q=await sql`SELECT 1 FROM property_garage_vehicles g JOIN vehicles v ON v.id=g.vehicle_id WHERE g.property_id=${id}::uuid AND g.vehicle_id=${vehicleId}::bigint AND v.owner_character_id=${c}`.execute(db());if(!q.rows.length)throw new Error('VEHICLE_NOT_FOUND');await spawnOwnedVehicle(c,p,vehicleId);await sql`DELETE FROM property_garage_vehicles WHERE property_id=${id}::uuid AND vehicle_id=${vehicleId}::bigint`.execute(db());return garage(c,id);};

export const furniture=async(c:number,id:string):Promise<PropertyFurnitureView[]>=>{accessible(await row(id),c);const q=await sql<any>`SELECT id::text,property_id::text,model,position_x::text,position_y::text,position_z::text,rotation_x::text,rotation_y::text,rotation_z::text FROM property_furniture WHERE property_id=${id}::uuid ORDER BY id`.execute(db());return q.rows.map((x:any)=>({id:x.id,propertyId:x.property_id,model:x.model,x:Number(x.position_x),y:Number(x.position_y),z:Number(x.position_z),rx:Number(x.rotation_x),ry:Number(x.rotation_y),rz:Number(x.rotation_z)}));};
export const placeFurniture=async(c:number,p:PlayerMp,id:string,input:{model:string;x:number;y:number;z:number;rx:number;ry:number;rz:number}):Promise<PropertyFurnitureView[]>=>{const r=await row(id);owner(r,c);if(p.dimension!==r.instance_dimension)throw new Error('PROPERTY_WRONG_INTERIOR');if(!/^[A-Za-z0-9_]{1,64}$/.test(input.model)||![input.x,input.y,input.z,input.rx,input.ry,input.rz].every(Number.isFinite))throw new Error('INVALID_FURNITURE');if(distance(p.position,input)>12)throw new Error('FURNITURE_TOO_FAR');const count=await sql<{n:string}>`SELECT COUNT(*)::text n FROM property_furniture WHERE property_id=${id}::uuid`.execute(db());if(Number(count.rows[0]?.n??0)>=100)throw new Error('FURNITURE_LIMIT');await sql`INSERT INTO property_furniture(property_id,model,position_x,position_y,position_z,rotation_x,rotation_y,rotation_z,placed_by) VALUES(${id}::uuid,${input.model},${input.x},${input.y},${input.z},${input.rx},${input.ry},${input.rz},${c})`.execute(db());return furniture(c,id);};
export const removeFurniture=async(c:number,id:string,furnitureId:string):Promise<PropertyFurnitureView[]>=>{const r=await row(id);owner(r,c);if(!/^\d+$/.test(furnitureId))throw new Error('INVALID_FURNITURE');const d=await sql`DELETE FROM property_furniture WHERE id=${furnitureId}::bigint AND property_id=${id}::uuid`.execute(db());if(Number(d.numAffectedRows??0)===0)throw new Error('INVALID_FURNITURE');return furniture(c,id);};
